SELECT 
  ITM_S.LOGICALREF 'SARF_LOGICALREF', 
  ITM_S.CARDTYPE 'SARF_CARDTYPE', 
  ITM_S.CODE 'SARF_CODE', 
  ITM_S.NAME 'SARF_NAME', 
  ITM_U.CARDTYPE 'URETIM_CARDTYPE', 
  ITM_U.CODE 'URETIM_CODE', 
  ITM_U.NAME 'URETIM_NAME', 
  ITM_U.SPECODE 'URETIM_SPECODE', 
  STC.AMNT 'SARF_AMMOUNT', 
  L.CODE 'SARF_UNIT' 
FROM 
  LG_${NS}_STCOMPLN STC WITH (NOLOCK) 
  LEFT OUTER JOIN LG_${NS}_ITEMS ITM_S WITH (NOLOCK) ON STC.STCREF = ITM_S.LOGICALREF 
  LEFT OUTER JOIN LG_${NS}_ITEMS ITM_U WITH (NOLOCK) ON ITM_U.LOGICALREF = STC.MAINCREF 
  LEFT OUTER JOIN LG_${NS}_UNITSETL L WITH (NOLOCK) ON L.LOGICALREF = STC.UOMREF 
WHERE 
  1 = 1
  ${WHERE}
