"""
 Tüm hakları BTI Bilişim Danışmanlık ve Yazılım Şirketi adına saklıdır.
 
"""

from . import LG_EMUHACC as Emuhacc
from . import LG_ACCCODES as Acccodes
from . import LG_CRDACREF as CardAccountRef
from . import LG_EMFICHE as Emfiche
from . import LG_LOGREP as Logrep
from . import LG_EMUHTOT as Emuhtot
from . import LG_EMFLINE as Emfline
from . import LG_ADDTAX as Addtax
from . import LG_ADDTAXLINE as Addtaxline
from . import LG_CSCARD as Cscard
from . import LG_CSROLL as Csroll
from . import LG_CSTRANS as Cstrans
from . import LG_CLCARD as Clcard
from . import LG_CLFICHE as Clfiche
from . import LG_CLINTEL as Clintel
from . import LG_CLTOTFIL as Cltotfil
from . import LG_CLRNUMS as Clrnums
from . import LG_CLFLINE as Clfline
from . import LG_FOLDER as Folder
from . import LG_EMGRPASS as Emgrpass
from . import LG_EMPGROUP as Emgroup
from . import LG_EMPLOYEE as Employee
from . import LG_ENGCLINE as Engcline
from . import LG_FIRMDOC as Firmdoc
from . import LG_LABORREQ as Laborreq
from . import LG_LNGEXCSETS as Lngexcsets
from . import LG_TRANSAC as Transac
from . import LG_PRDCOST as Prdcost
from . import LG_PROJECT as Project
from . import LG_SHIPINFO as Shipinfo
from . import LG_TRGPAR as Trgpar
from . import LG_SELCHVAL as Selchval
from . import LG_ITMBOMAS as Itmbomas
from . import LG_ITMCLSAS as Itmclsas
from . import LG_STINVTOT as Stinvtot
from . import LG_ITMFACTP as Itmfactp
from . import LG_INVDEF as Invdef
from . import LG_CHARASGN as Charasgn
from . import LG_CHARCODE as Charcode
from . import LG_CHARVAL as Charval
from . import LG_ITEMS as Items
from . import LG_ITEMSUBS as Itemsubs
from . import LG_SERILOTN as Serilotn
from . import LG_SLTRANS as Sltrans
from . import LG_STCOMPLN as Stcompln
from . import LG_STINVENS as Stinvens
from . import LG_SUPPASGN as Suppasgn
from . import LG_ITMUNITA as Itmunita
from . import LG_ACTIVITYAMNT as Activityamtn
from . import LG_WSGRPF as Wsgrpf
from . import LG_WSGRPASS as Wsgrpass
from . import LG_PRVOPASG as Prvopasg
from . import LG_PRODORD as Prodord
from . import LG_PEGGING as Pegging
from . import LG_BOMASTER as Bomaster
from . import LG_BOMLINE as Bomline
from . import LG_BOMPARAM as Bomparam
from . import LG_COPRDBOM as Coprdbom
from . import LG_ROUTING as Routing
from . import LG_RTNGLINE as Rtngline
from . import LG_DISPLINE as Displine
from . import LG_WORKSTAT as Workstat
from . import LG_WSATTASG as Wsattasg
from . import LG_WSATTVAS as Wsattvas
from . import LG_WSCHCODE as Wschcode
from . import LG_WSCHVAL as Wschval
from . import LG_QASGN as Qasgn
from . import LG_QCLVAL as Qclval
from . import LG_SLQCASGN as Slqcasgn
from . import LG_QCSET as Qcset
from . import LG_QCSLINE as Qscline
from . import LG_CONTACTS as Contacs
from . import LG_DISTLINE as Distline
from . import LG_DISTTEMP as Disttemp
from . import LG_LNOPASGN as Lnopasgn
from . import LG_LOCATION as Location
from . import LG_OPERTION as Opertion
from . import LG_OPRTREQ as Oprtreq
from . import LG_OPATTASG as Opattasg
from . import LG_ACTPEPL as Actpepl
from . import LG_ROUTETRS as Routetrs
from . import LG_ROUTE as Route
from . import LG_SLSMAN as Slsman
from . import LG_SLSCLREL as Slsclrel
from . import LG_TARGETS as Targets
from . import LG_TOOLREQ as Toolreq
from . import LG_EARCHIVEDET as EarchiveDet
from . import LG_STFICHE as Stfiche
from . import LG_INVOICE as Invoice
from . import LG_SRVTOT as Srvtot
from . import LG_ORFICHE as Orfiche
from . import LG_ORFLINE as Orfline
from . import LG_PRODUCER as Producer
from . import LG_STLINE as Stline
from . import LG_SRVNUMS as Srvnums
from . import LG_CATEGLISTS as Categlists
from . import LG_USAGESTAT as Usagestat
from . import LG_ASCOND as Ascond
from . import LG_DECARDS as Decards
from . import LG_DEMANDFICHE as Demandfiche
from . import LG_DEMANDLINE as Demandline
from . import LG_DEMANDPEGGING as Demandpegging
from . import LG_EMCENTER as Emcenter
from . import LG_PAYLINES as Paylines
from . import LG_PAYPLANS as Payplans
from . import LG_PRCARDS as Prcards
from . import LG_PRCLIST as Prclist
from . import LG_PAYTRANS as Paytrans
from . import LG_SPECODES as Specodes
from . import LG_SRVCARD as Srvcard
from . import LG_UNITSETF as Unitsetf
from . import LG_UNITSETL as Unitsetl
from . import LG_SRVUNITA as Srvunita
from . import LG_UNITSETC as Unitsetc
from . import LG_WFTASK as Wftask
from . import LG_FAREGIST as Faregist
from . import LG_FAYEAR as Fayear
from . import LG_BANKACC as Bankacc
from . import LG_BNCARD as Bncard
from . import LG_BNFICHE as Bnfiche
from . import LG_BNTOTFIL as Bntotfil
from . import LG_BNFLINE as Bnfline
from . import LG_KSCARD as Kscard
from . import LG_CSHTOTS as Cshtots
from . import LG_KSLINES as Kslines
from . import LG_CAMPAIGN as Campaign
from . import LG_HISTORY as History
from . import LG_EBOOKDETAILDOC as EbookDetailDoc
from . import LG_UNITBARCODE as UnitBarcode

from . import L_COUNTRY as Country
from . import L_CITY as City
from . import L_TOWN as Town
from . import L_DISTRICT as District
from . import L_POSTCODE as Postcode
from . import L_BANKCODE as Bankcode
from . import L_BNBRANCH as Bnbranch
from . import L_STATUSINFO as Statusinfo
from . import L_CAPITERMINAL as Capiterminal
from . import L_TRADGRP as Tradgrp
from . import L_CAPIUNIT as Capiunit
from . import L_CAPIVERS as Capivers
from . import L_CAPIWHOUSE as Capiwhouse
from . import L_CURRENCYLIST as Currencylist
from . import L_CURRENCYPARS as Currencypars
from . import L_CAPIDEPT as Capidep
from . import L_CAPIDIV as Capidiv
from . import L_LDOCNUM as Ldocnum
from . import L_DAILYEXCHANGES as Dailyexchanges
from . import L_CAPIFACTORY as Capifactory
from . import L_CAPIFACTDIV as Capifactdiv
from . import L_CAPIFIRM as Capifirm
from . import L_FIRMPARAMS as Firmparams
from . import L_CAPIGROUP as Capigroup
from . import L_CAPIUSER as Capiuser
from . import L_GOUSERS as Gousers
from . import L_NET as Net
from . import L_CAPIPERIOD as Capiperiod
from . import L_DYNREP as Dynrep
from . import L_DYNREPUSRR as Dynrepusrr
from . import L_CAPIROLE as Capirole
from . import L_SHPAGENT as Shpagent
from . import L_SHPTYPES as Shptypes
