"""
 Tüm hakları BTI Bilişim Danışmanlık ve Yazılım Şirketi adına saklıdır.
 
"""

from erp.integration import base

class MaterialLineDetail(base.BaseSerialiazer):
	ITEM_CODE = base.CharField(label="Malzeme kodu", table="LG_ITEMS",field="CODE",max_length=25,required=False)
	ITEM_REFERENCE = base.IntegerField(label="Malzeme referansı", table="LG_STLINE",field="STOCKREF",required=False)
	LINE_TYPE = base.IntegerField(label="Satır türü", table="LG_STLINE",field="LINETYPE",min_value=0, max_value=1,required=False)
	DETAIL_LEVEL = base.IntegerField(label="Malzeme sınıfı detay satırı", table="LG_STLINE",field="DETLINE",min_value=0, max_value=1,required=False)
	DISCEXP_CALC = base.IntegerField(label="İndirim/masraf hesaplama", table="LG_STLINE",field="CALCTYPE",min_value=0, max_value=1,required=False)
	LINE_NUMBER = base.IntegerField(label="Satır numarası", table="LG_STLINE",field="STFICHELNNO",required=False)
	GL_CODE1 = base.CharField(label="Muhasebe hesap kodu 1", table="LG_EMUHACC",field="CODE",max_length=25,required=False)
	OHP_CODE1 = base.CharField(label="Masraf merkezi 1", table="LG_EMCENTER",field="CODE",max_length=17,required=False)
	GL_CODE2 = base.CharField(label="Muhasebe hesap kodu 2", table="LG_EMUHACC",field="CODE",max_length=25,required=False)
	OHP_CODE2 = base.CharField(label="Masraf merkezi kodu 2", table="LG_EMCENTER",field="CODE",max_length=17,required=False)
	GL_CODE3 = base.CharField(label="Muhasebe hesap kodu 3", table="LG_EMUHACC",field="CODE",max_length=25,required=False)
	OHP_CODE3 = base.CharField(label="Masraf merkezi kodu 3", table="LG_EMCENTER",field="CODE",max_length=17,required=False)
	GL_CODE4 = base.CharField(label="Muhasebe hesap kodu 4", table="LG_EMUHACC",field="CODE",max_length=25,required=False)
	OHP_CODE4 = base.CharField(label="Masraf merkezi kodu 4", table="LG_EMCENTER",field="CODE",max_length=17,required=False)
	AUXIL_CODE = base.CharField(label="Özel kod", table="LG_STLINE",field="SPECODE",max_length=17,required=False)
	DELVRY_CODE = base.CharField(label="Teslimat kodu", table="LG_STLINE",field="DELVRYCODE",max_length=5,required=False)
	QUANTITY = base.FloatField(label="Miktar", table="LG_STLINE",field="AMOUNT",required=False)
	PRICE = base.FloatField(label="Birim fiyat", table="LG_STLINE",field="PRICE",required=False)
	TOTAL = base.FloatField(label="Toplam", table="LG_STLINE",field="TOTAL",required=False)
	NET_TOTAL = base.FloatField(label="Net toplam", table="LG_STLINE",field="LINENET",required=False)
	CURR_PRICE = base.IntegerField(label="Dövizli birim fiyat", table="LG_STLINE",field="PRCURR",min_value=0, max_value=1,required=False)
	PC_PRICE = base.FloatField(label="Fiyatlandırma dövizi", table="LG_STLINE",field="PRPRICE",required=False)
	CURR_TRANS = base.IntegerField(label="İşlem dövizi türü", table="LG_STLINE",field="TRCURR",min_value=0, max_value=1,required=False)
	TC_XRATE = base.FloatField(label="İşlem dövizi kuru", table="LG_STLINE",field="TRRATE",required=False)
	RC_XRATE = base.FloatField(label="Raporlama dövizi kuru", table="LG_STLINE",field="REPORTRATE",required=False)
	TCOST_DISTR = base.FloatField(label="İşlem maliyet dağılımı", table="LG_STLINE",field="DISTCOST",required=False)
	DISCOUNT_DISTR = base.FloatField(label="Dağıtılan indirim", table="LG_STLINE",field="DISTDISC",required=False)
	EXPENSE_DISTR = base.FloatField(label="Dağıtılan masraf", table="LG_STLINE",field="DISTEXP",required=False)
	PROMOTION_DISTR = base.FloatField(label="Dağıtılan promosyon", table="LG_STLINE",field="DISTPROM",required=False)
	DISCOUNT_PERC = base.FloatField(label="Masraf yüzdesi", table="LG_STLINE",field="DISCPER",required=False)
	DESCRIPTION = base.CharField(label="Açıklama", table="LG_STLINE",field="LINEEXP",max_length=31,required=False)
	UNIT_CODE = base.CharField(label="Birim kodu", table="LG_UNITSETL",field="CODE",max_length=11,required=True)
	UNIT_CONV1 = base.FloatField(label="Çevrim katsayısı1", table="LG_STLINE",field="UINFO1",required=True)
	UNIT_CONV2 = base.FloatField(label="Çevrim katsayısı2", table="LG_STLINE",field="UINFO2",required=True)
	UNIT_CONV3 = base.FloatField(label="Boyut katsayısı3", table="LG_STLINE",field="UINFO3",required=False)
	UNIT_CONV4 = base.FloatField(label="Boyut katsayısı4", table="LG_STLINE",field="UINFO4",required=False)
	UNIT_CONV5 = base.FloatField(label="Boyut katsayısı5", table="LG_STLINE",field="UINFO5",required=False)
	UNIT_CONV6 = base.FloatField(label="Boyut katsayısı6", table="LG_STLINE",field="UINFO6",required=False)
	UNIT_CONV7 = base.FloatField(label="Boyut katsayısı7", table="LG_STLINE",field="UINFO7",required=False)
	UNIT_CONV8 = base.FloatField(label="Boyut katsayısı8", table="LG_STLINE",field="UINFO8",required=False)
	VAT_INCLUDED = base.IntegerField(label="KDV dahil / hariç", table="LG_STLINE",field="VATINC",min_value=0, max_value=1,required=False)
	VAT_PERC = base.FloatField(label="KDVyüzdesi", table="LG_STLINE",field="VAT",required=False)
	VAT_AMNT = base.FloatField(label="KDVtutarı", table="LG_STLINE",field="VATAMNT",required=False)
	COMPOSITE = base.IntegerField(label="Karma koli", table="LG_STLINE",field="CPSTFLAG",min_value=0, max_value=1,required=False)
	RET_COST_TYPE = base.IntegerField(label="İade maliyet türü", table="LG_STLINE",field="RETCOSTTYPE",min_value=0, max_value=3,required=False)
	RET_COST = base.FloatField(label="İade maliyeti", table="LG_STLINE",field="RETCOST",required=False)
	CURR_RET_COST = base.FloatField(label="Dövizli iade maliyeti", table="LG_STLINE",field="RETCOSTCURR",required=False)
	OUT_COST = base.FloatField(label="Çıkış maliyeti", table="LG_STLINE",field="OUTCOST",required=False)
	CURR_OUT_COST = base.FloatField(label="Dövizli çıkış maliyeti", table="LG_STLINE",field="OUTCOSTCURR",required=False)
	RET_QUANTITY = base.FloatField(label="İade miktarı", table="LG_STLINE",field="RETAMOUNT",required=False)
	FAREG_CODE = base.CharField(label="Sabit kıymet kodu", table="LG_FAREGIST",field="REGCODE",max_length=17,required=False)
	FA_STATUS = base.IntegerField(label="Sabit kıymet statüsü", table="LG_STLINE",field="FAATTRIB",min_value=0, max_value=1,required=False)
	CANCELLED = base.IntegerField(label="İptal edilenler", table="LG_STLINE",field="CANCELLED",min_value=0, max_value=1,required=False)
	PRICE_ADJUSTMENT = base.FloatField(label="Fiyat farkı toplamı", table="LG_STLINE",field="DIFFPRICE",required=False)
	COST_ADJUSTMENT_PR = base.FloatField(label="Fiyat farkı maliyeti", table="LG_STLINE",field="DIFFPRCOST",required=False)
	NEGPRC_ADJUSTMENT = base.IntegerField(label="Fiyat farkı", table="LG_STLINE",field="DECPRDIFF",min_value=0, max_value=1,required=False)
	RC_PRJADJUST = base.FloatField(label="Toplu fiyat farkı (Raporlama dövizi)", table="LG_STLINE",field="DIFFREPPRICE",required=False)
	RC_COSTADJUST = base.FloatField(label="Fiyat Farkı Maliyeti (Raporlama Dövizi)", table="LG_STLINE",field="DIFFPRCRCOST",required=False)
	OUTPUT_IDCODE = base.CharField(label="Çıkış izleme kodu", table="LG_STLINE",field="OUTPUTIDCODE",max_length=25,required=False)
	COST_RATE = base.FloatField(label="Maliyet yüzdesi", table="LG_STLINE",field="COSTRATE",required=False)
	QC_STATUS = base.FloatField(label="Kalite kontrol durumu", table="LG_STLINE",field="TRANSQCOK",required=False)
	DATA_SITEID = base.IntegerField(label="Veri merkezi", table="LG_STLINE",field="SITEID",required=False)

class MaterialLineSlDetail(base.BaseSerialiazer):
	SOURCE_MT_REFERENCE = base.IntegerField(label="Input Item Transaction Reference", table="LG_SLTRANS",field="INTRANSREF",required=False)
	SOURCE_SLT_REFERENCE = base.IntegerField(label="Input Lot / Serial / Location Transaction Reference", table="LG_SLTRANS",field="INSLTRANSREF",required=False)
	SOURCE_QUANTITY = base.FloatField(label="Quantity From Input Transaction Unit", table="LG_SLTRANS",field="INSLAMOUNT",required=False)
	SOURCE_WH = base.IntegerField(label="Ambar numarası", table="LG_SLTRANS",field="INVENNO",required=False)
	SL_TYPE = base.IntegerField(label="Seri / Lot Türü 1. Lot, 2. Seri", table="LG_SLTRANS",field="SLTYPE",required=False)
	SL_CODE = base.CharField(label="Seri / Lot kodu", table="LG_SERILOTN",field="CODE",max_length=25,required=False)
	LOCATION_CODE = base.CharField(label="Stok yeri kodu", table="LG_LOCATION",field="CODE",max_length=25,required=False)
	DEST_LOCATION_CODE = base.CharField(label="Stok yeri açıklaması", table="LG_LOCATION",field="NAME",max_length=51,required=False)
	MU_QUANTITY = base.FloatField(label="Ana birim miktarı", table="LG_SLTRANS",field="MAINAMOUNT",required=False)
	UNIT_CODE = base.CharField(label="Birim kodu", table="LG_UNITSETL",field="CODE",max_length=11,required=False)
	QUANTITY = base.FloatField(label="Satır birim miktarı", table="LG_SLTRANS",field="AMOUNT",required=False)
	REM_QUANTITY = base.FloatField(label="Ana birim kalan miktar", table="LG_SLTRANS",field="REMAMOUNT",required=False)
	LU_REM_QUANTITY = base.FloatField(label="Ana birim satır miktarı", table="LG_SLTRANS",field="REMLNUNITAMNT",required=False)
	UNIT_CONV1 = base.FloatField(label="Çevrim katsayısı1", table="LG_SLTRANS",field="UINFO1",required=False)
	UNIT_CONV2 = base.FloatField(label="Çevrim katsayısı2", table="LG_SLTRANS",field="UINFO2",required=False)
	UNIT_CONV3 = base.FloatField(label="Boyut katsayısı3", table="LG_SLTRANS",field="UINFO3",required=False)
	UNIT_CONV4 = base.FloatField(label="Boyut katsayısı4", table="LG_SLTRANS",field="UINFO4",required=False)
	UNIT_CONV5 = base.FloatField(label="Boyut katsayısı5", table="LG_SLTRANS",field="UINFO5",required=False)
	UNIT_CONV6 = base.FloatField(label="Boyut katsayısı6", table="LG_SLTRANS",field="UINFO6",required=False)
	UNIT_CONV7 = base.FloatField(label="Boyut katsayısı7", table="LG_SLTRANS",field="UINFO7",required=False)
	UNIT_CONV8 = base.FloatField(label="Boyut katsayısı8", table="LG_SLTRANS",field="UINFO8",required=False)
	DATE_EXPIRED = base.IntegerField(label="Son Kullanım Tarihi", table="LG_SLTRANS",field="EXPDATE",required=False)
	RATE_SCORE = base.IntegerField(label="Note", table="LG_SLTRANS",field="RATESCORE",required=False)
	OUT_COST = base.FloatField(label="Çıkış fişleri çıkış maliyeti", table="LG_SLTRANS",field="OUTCOST",required=False)
	TC_OUT_COST = base.FloatField(label="Çıkış fişleri çıkış maliyeti (Döviz)", table="LG_SLTRANS",field="OUTCOSTCURR",required=False)
	PRCDIF_COST = base.FloatField(label="Fiyat farkı maliyeti", table="LG_SLTRANS",field="DIFFPRCOST",required=False)
	TC_PRCDIF_COST = base.FloatField(label="Cost In F. Currency Because Of Price Difference", table="LG_SLTRANS",field="DIFFPRCOSTCURR",required=False)
	SL_QC_OK = base.IntegerField(label="Uygunluk kontrolü", table="LG_SLTRANS",field="SERIQCOK",min_value=0, max_value=1,required=False)
	SOURCE_TYPE = base.IntegerField(label="Kaynak türü (0- Ambar, 1- İş İstasyonu)", table="LG_SLTRANS",field="SOURCETYPE",min_value=0, max_value=1,required=False)
	DATA_SITEID = base.IntegerField(label="Veri merkezi", table="LG_SLTRANS",field="SITEID",required=False)

class MaterialLineTransaction(base.BaseSerialiazer):
	ITEM_CODE = base.CharField(label="Malzeme kodu", table="LG_ITEMS",field="CODE",max_length=25,required=False)
	ITEM_REFERENCE = base.IntegerField(label="Malzeme referansı", table="LG_STLINE",field="STOCKREF",required=False)
	LINE_TYPE = base.IntegerField(label="Satır türü", table="LG_STLINE",field="LINETYPE",min_value=0, max_value=1,required=False)
	DETAIL_LEVEL = base.IntegerField(label="Malzeme Sınıfı Detay Satırı", table="LG_STLINE",field="DETLINE",min_value=0, max_value=1,required=False)
	DISCEXP_CALC = base.IntegerField(label="İndirim/masraf hesaplaması", table="LG_STLINE",field="CALCTYPE",min_value=0, max_value=1,required=False)
	PRORD_SITE = base.IntegerField(label="Üretim emri referansı", table="LG_STLINE",field="PRODORDERREF",required=False)
	PRORD_REFERENCE = base.IntegerField(label="Üretim emri satır referansı", table="LG_STLINE",field="POLINEREF",required=False)
	LINE_NUMBER = base.IntegerField(label="Satır numarası", table="LG_STLINE",field="STFICHELNNO",required=False)
	GL_CODE1 = base.CharField(label="Muhasebe kodu1", table="LG_EMUHACC",field="CODE",max_length=25,required=False)
	OHP_CODE1 = base.CharField(label="Masraf merkezi kodu1", table="LG_EMCENTER",field="CODE",max_length=17,required=False)
	GL_CODE2 = base.CharField(label="Muhasebe kodu2", table="LG_EMUHACC",field="CODE",max_length=25,required=False)
	OHP_CODE2 = base.CharField(label="Masraf merkezi kodu2", table="LG_EMCENTER",field="CODE",max_length=17,required=False)
	GL_CODE3 = base.CharField(label="Muhasebe kodu3", table="LG_EMUHACC",field="CODE",max_length=25,required=False)
	OHP_CODE3 = base.CharField(label="Masraf merkezi kodu3", table="LG_EMCENTER",field="CODE",max_length=17,required=False)
	GL_CODE4 = base.CharField(label="Muhasebe kodu4", table="LG_EMUHACC",field="CODE",max_length=25,required=False)
	OHP_CODE4 = base.CharField(label="Masraf merkezi kodu4", table="LG_EMCENTER",field="CODE",max_length=17,required=False)
	AUXIL_CODE = base.CharField(label="Özel kod", table="LG_STLINE",field="SPECODE",max_length=17,required=False)
	DELVRY_CODE = base.CharField(label="Teslimat kodu", table="LG_STLINE",field="DELVRYCODE",max_length=5,required=False)
	QUANTITY = base.FloatField(label="Miktar", table="LG_STLINE",field="AMOUNT",required=False)
	PRICE = base.FloatField(label="Birim fiyat", table="LG_STLINE",field="PRICE",required=False)
	TOTAL = base.FloatField(label="Toplam", table="LG_STLINE",field="TOTAL",required=False)
	NET_TOTAL = base.FloatField(label="Net toplam", table="LG_STLINE",field="LINENET",required=False)
	CURR_PRICE = base.IntegerField(label="Dövizli birim fiyatı", table="LG_STLINE",field="PRCURR",min_value=0, max_value=1,required=False)
	PC_PRICE = base.FloatField(label="Fiyatlandırma dövizi", table="LG_STLINE",field="PRPRICE",required=False)
	CURR_TRANS = base.IntegerField(label="Kur aktarımı", table="LG_STLINE",field="TRCURR",min_value=0, max_value=1,required=False)
	TC_XRATE = base.FloatField(label="İşlem dövizi kuru", table="LG_STLINE",field="TRRATE",required=False)
	RC_XRATE = base.FloatField(label="Raporlama dövizi kuru", table="LG_STLINE",field="REPORTRATE",required=False)
	TCOST_DIST = base.FloatField(label="Toplam indirim dağıtımı", table="LG_STLINE",field="DISTCOST",required=False)
	DISCOUNT_DISTR = base.FloatField(label="Dağıtılan indirimler", table="LG_STLINE",field="DISTDISC",required=False)
	EXPENSE_DISTR = base.FloatField(label="Dağıtılan masraflar", table="LG_STLINE",field="DISTEXP",required=False)
	PROMOTION_DISTR = base.FloatField(label="Dağıtılan promosyonlar", table="LG_STLINE",field="DISTPROM",required=False)
	DISCOUNT_PERCENT = base.FloatField(label="Dağılım yüzdesi", table="LG_STLINE",field="DISCPER",required=False)
	DESCRIPTION = base.CharField(label="Açıklama", table="LG_STLINE",field="LINEEXP",max_length=31,required=False)
	UNIT_CODE = base.CharField(label="Birim kodu", table="LG_UNITSETL",field="CODE",max_length=11,required=False)
	UNIT_CONV1 = base.FloatField(label="Birim çevrimi1", table="LG_STLINE",field="UINFO1",required=False)
	UNIT_CONV2 = base.FloatField(label="Birim çevrimi2", table="LG_STLINE",field="UINFO2",required=False)
	UNIT_CONV3 = base.FloatField(label="Birim çevrimi3", table="LG_STLINE",field="UINFO3",required=False)
	UNIT_CONV4 = base.FloatField(label="Birim çevrimi4", table="LG_STLINE",field="UINFO4",required=False)
	UNIT_CONV5 = base.FloatField(label="Birim çevrimi5", table="LG_STLINE",field="UINFO5",required=False)
	UNIT_CONV6 = base.FloatField(label="Birim çevrimi6", table="LG_STLINE",field="UINFO6",required=False)
	UNIT_CONV7 = base.FloatField(label="Birim çevrimi7", table="LG_STLINE",field="UINFO7",required=False)
	UNIT_CONV8 = base.FloatField(label="Birim çevrimi8", table="LG_STLINE",field="UINFO8",required=False)
	VAT_INCLUDED = base.IntegerField(label="KDV dahil / hariç", table="LG_STLINE",field="VATINC",min_value=0, max_value=1,required=False)
	VAT_PERC = base.FloatField(label="KDV yüzde", table="LG_STLINE",field="VAT",required=False)
	VAT_AMNT = base.FloatField(label="KDV tutarı", table="LG_STLINE",field="VATAMNT",required=False)
	COMPOSITE = base.IntegerField(label="Karma koli", table="LG_STLINE",field="CPSTFLAG",min_value=0, max_value=1,required=False)
	RET_COST_TYPE = base.IntegerField(label="İade maliyeti türü", table="LG_STLINE",field="RETCOSTTYPE",min_value=0, max_value=3,required=False)
	RET_COST = base.FloatField(label="İade maliyeti", table="LG_STLINE",field="RETCOST",required=False)
	CURR_RET_COST = base.FloatField(label="Dövizli iade maliyeti", table="LG_STLINE",field="RETCOSTCURR",required=False)
	OUT_COST = base.FloatField(label="Çıkış maliyeti", table="LG_STLINE",field="OUTCOST",required=False)
	CURR_OUT_COST = base.FloatField(label="Dövizli çıkış maliyeti", table="LG_STLINE",field="OUTCOSTCURR",required=False)
	RET_QUANTITY = base.FloatField(label="İade miktarı", table="LG_STLINE",field="RETAMOUNT",required=False)
	FAREG_CODE = base.CharField(label="Sabit kıymet iade kodu", table="LG_ITEMS",field="CODE",max_length=25,required=False)
	FA_STATUS = base.IntegerField(label="Sabit kıymet statüsü", table="LG_STLINE",field="FAATTRIB",min_value=0, max_value=1,required=False)
	CANCELLED = base.IntegerField(label="İptal edildi", table="LG_STLINE",field="CANCELLED",min_value=0, max_value=1,required=False)
	PRICE_ADJUSMENT = base.FloatField(label="Fiyat güncellemeleri", table="LG_STLINE",field="DIFFPRICE",required=False)
	COST_ADJUSTMENT_PR = base.FloatField(label="Fiyat farkı maliyeti", table="LG_STLINE",field="DIFFPRCOST",required=False)
	NEGPRC_ADJUSTMENT = base.IntegerField(label="Fiyat Farkı", table="LG_STLINE",field="DECPRDIFF",min_value=0, max_value=1,required=False)
	RC_PRJADJUST = base.FloatField(label="Toplam fiyat farkı (Rap. Dövizi)", table="LG_STLINE",field="DIFFREPPRICE",required=False)
	RC_COSTADJUST = base.FloatField(label="Fiyat Farkı Maliyeti (Raporlama Dövizi)", table="LG_STLINE",field="DIFFPRCRCOST",required=False)
	OUTPUT_IDCODE = base.CharField(label="Çıkış izleme kodu", table="LG_STLINE",field="OUTPUTIDCODE",max_length=25,required=False)
	COST_RATE = base.FloatField(label="Maliyet oranı", table="LG_STLINE",field="COSTRATE",required=False)
	QC_STATUS = base.IntegerField(label="Kalite kontrol durumu", table="LG_STLINE",field="TRANSQCOK",min_value=0, max_value=1,required=False)
	DATA_SITEID = base.IntegerField(label="Veri merkezi", table="LG_STLINE",field="SITEID",required=False)

	SOURCEINDEX = base.IntegerField(label='?', table="LG_STLINE",field='SOURCEINDEX',required=False)
	RELTRANSLNREF = base.IntegerField(label="?", required=False)
	FROMTRANSFER = base.IntegerField(label="?", required=False)

	#SL_DETAILS = MaterialLineSlDetail(many=True)
	#DETAILS = MaterialLineSlDetail(many=True)

class MaterialLineTransactionHolder(base.BaseSerialiazer):
	items = base.serializers.ListSerializer(child=MaterialLineTransaction())

class BaseMaterial(base.Serializer):
	GROUP = base.IntegerField(label="Grup", table="LG_STFICHE",field="GRPCODE",required=False)
	TYPE = base.IntegerField(label="Fiş türü", table="LG_STFICHE",field="TRCODE",required=True)
	NUMBER = base.CharField(label="Fiş numarası", table="LG_STFICHE",field="FICHENO",max_length=17,required=True)
	DOC_TRACK_NR = base.CharField(label="Doküman İzleme Numarası", table="LG_STFICHE",field="DOCTRACKINGNR",max_length=21,required=False)
	DATE = base.CharField(label="Fiş tarihi", table="LG_STFICHE",field="DATE_",required=False)
	TIME = base.IntegerField(label="Fiş kayıt zamanı", table="LG_STFICHE",field="FTIME",required=False)
	DOC_NUMBER = base.CharField(label="Belge numarası", table="LG_STFICHE",field="DOCODE",max_length=32,required=False)
	AUXIL_CODE = base.CharField(label="Fiş özel kodu", table="LG_STFICHE",field="SPECODE",max_length=11,required=False)
	AUTH_CODE = base.CharField(label="Fiş yetki kodu", table="LG_STFICHE",field="CYPHCODE",max_length=11,required=False)
	PORDER_FICHE_NR = base.CharField(label="Üretim Emri numarası", table="LG_PRODORD",field="FICHENO",max_length=17,required=False)
	SOURCE_TYPE = base.IntegerField(label="Kaynak türü", table="LG_STFICHE",field="SOURCETYPE",min_value=0, max_value=1,required=False)
	SOURCE_WH = base.CharField(label="Kaynak ambarı", table="LG_STFICHE",field="SOURCEINDEX",required=False)
	SOURCE_WSCODE = base.CharField(label="Kaynak iş istasyonu kodu", table="LG_WORKSTAT",field="CODE",max_length=4,required=False)
	SPO_DETAIL_CODE = base.CharField(label="Kaynak üretim emri numarası", table="LG_DISPLINE",field="LINENO_",max_length=4,required=False)
	SOURCE_COST_GRP = base.IntegerField(label="Kaynak maliyet grubu", table="LG_STFICHE",field="SOURCECOSTGRP",required=False)
	DEST_TYPE = base.IntegerField(label="Hedef türü", table="LG_STFICHE",field="DESTTYPE",min_value=0, max_value=1,required=False)
	DEST_WH = base.CharField(label="Hedef ambarı", table="LG_STFICHE",field="DESTINDEX",required=False)
	DEST_WSCODE = base.CharField(label="Hedef iş iş istasyonu kodu", table="LG_WORKSTAT",field="CODE",max_length=4,required=False)
	DPO_DETAIL_CODE = base.CharField(label="Hedef üretim emri numarası", table="LG_DISPLINE",field="LINENO_",max_length=4,required=False)
	DEST_COST_GRP = base.IntegerField(label="Hedef maliyet grubu", table="LG_STFICHE",field="DESTCOSTGRP",required=False)
	SOURCE_FACTORY_NR = base.IntegerField(label="Kaynak fabrika numarası", table="LG_STFICHE",field="FACTORYNR",required=False)
	SOURCE_DIVISION_NR = base.IntegerField(label="Kaynak işyerin umarası", table="LG_STFICHE",field="BRANCH",required=False)
	SOURCE_DEPARTMENT_NR = base.IntegerField(label="Kaynak bölüm numarası", table="LG_STFICHE",field="DEPARTMENT",required=False)
	DEST_DIVISION_NR = base.IntegerField(label="Hedef işyeri numarası", table="LG_STFICHE",field="COMPBRANCH",required=False)
	DEST_DEPARTMENT_NR = base.IntegerField(label="Hedef bölümnumarası", table="LG_STFICHE",field="COMPDEPARTMENT",required=False)
	DEST_FACTORY = base.IntegerField(label="Hedef fabrika numarası", table="LG_STFICHE",field="COMPFACTORY",required=False)
	PORDER_STATUS = base.IntegerField(label="Satınalma siparişi durumu", table="LG_STFICHE",field="PRODSTAT",required=False)
	FY_TRANSFER = base.IntegerField(label="Devir", table="LG_STFICHE",field="DEVIR",min_value=0, max_value=1,required=False)
	CANCELLED = base.IntegerField(label="İptal edilenler", table="LG_STFICHE",field="CANCELLED",min_value=0, max_value=1,required=False)
	GL_STATUS = base.IntegerField(label="Muhasebe hesap durumu", table="LG_STFICHE",field="ACCOUNTED",min_value=0, max_value=1,required=False)
	XRATE_STATUS = base.IntegerField(label="Kur durumu", table="LG_STFICHE",field="UPDCURR",min_value=0, max_value=1,required=False)
	ADD_DISCOUNTS = base.FloatField(label="Fiş geneline ait ek indirimler", table="LG_STFICHE",field="ADDDISCOUNTS",required=False)
	TOTAL_DISCOUNTS = base.FloatField(label="İndirimler toplamı", table="LG_STFICHE",field="TOTALDISCOUNTS",required=False)
	ADD_EXPENSES = base.FloatField(label="Fiş geneline uygulanan ek masraflar", table="LG_STFICHE",field="ADDEXPENSES",required=False)
	TOTAL_EXPENSES = base.FloatField(label="Toplam masraflar", table="LG_STFICHE",field="TOTALEXPENSES",required=False)
	TOTAL_DEPOSITED = base.FloatField(label="Depozito toplamı", table="LG_STFICHE",field="TOTALDEPOZITO",required=False)
	TOTAL_PROMOTIONS = base.FloatField(label="Toplam promosyonlar", table="LG_STFICHE",field="TOTALPROMOTIONS",required=False)
	FOOTNOTE1 = base.CharField(label="Açıklama1", table="LG_STFICHE",field="GENEXP1",max_length=51,required=False)
	FOOTNOTE2 = base.CharField(label="Açıklama2", table="LG_STFICHE",field="GENEXP2",max_length=51,required=False)
	FOOTNOTE3 = base.CharField(label="Açıklama3", table="LG_STFICHE",field="GENEXP3",max_length=51,required=False)
	FOOTNOTE4 = base.CharField(label="Açıklama4", table="LG_STFICHE",field="GENEXP4",max_length=51,required=False)
	RC_RATE = base.FloatField(label="Raporlama dövizi kuru", table="LG_STFICHE",field="REPORTRATE",required=False)
	PRINT_COUNTER = base.IntegerField(label="Basım sayısı", table="LG_STFICHE",field="PRINTCNT",required=False)
	GL_CANCELLED = base.IntegerField(label="Muhasebeleştirme iptali", table="LG_STFICHE",field="CANCELLEDACC",min_value=0, max_value=1,required=False)
	SHIPMENT_TYPE = base.CharField(label="Teslimat türü", table="LG_STFICHE",field="SHPTYPCOD",max_length=13,required=False)
	SHIPPING_AGENT = base.CharField(label="Taşıyıcı firma", table="LG_STFICHE",field="SHPAGNCOD",max_length=13,required=False)
	TRACK_NO = base.CharField(label="İzleme numarası", table="LG_STFICHE",field="TRACKNR",max_length=17,required=False)
	CURRSEL_TOTALS = base.IntegerField(label="Genel Döviz Türü", table="LG_STFICHE",field="GENEXCTYP",required=False)
	CURRSEL_DETAILS = base.IntegerField(label="Satır Döviz Türü", table="LG_STFICHE",field="LINEEXCTYP",required=False)
	TRADING_GROUP = base.CharField(label="Ticari işlem grubu", table="LG_STFICHE",field="TRADINGGRP",max_length=17,required=False)
	DATA_SITEID = base.IntegerField(label="Veri merkezi", table="LG_STFICHE",field="SITEID",required=False)
	SHIP_DATE = base.CharField(label='Sevkiyat tarihi', required=False)
	SHIP_TIME = base.IntegerField(label='Sevkiyat zamanı', required=False)

	FROMTRANSFER = base.IntegerField(label="?", required=False)



class BaseMaterialForJSON(BaseMaterial):
	TRANSACTIONS = MaterialLineTransactionHolder()

class BaseMaterialForXML(BaseMaterial):
	TRANSACTIONS = base.serializers.ListSerializer(child=MaterialLineTransaction())
	

class MaterialFiche(BaseMaterialForJSON):
	"""
		Malzeme fişi
	"""
	class Meta:
		XML_ROOT = "MATERIAL_SLIPS"
		XML_SUBROOT = "SLIP"
		XML_OP = "INS"
		DATA_OBJECT = "doMaterialSlip"
		REST_ENDPOINT = "itemSlips"
		RELATED_TABLE = 'LG_STFICHE'	


class MaterialFicheXML(BaseMaterialForXML):
	"""
		Malzeme fişi
	"""
	class Meta:
		XML_ROOT = "MATERIAL_SLIPS"
		XML_SUBROOT = "SLIP"
		XML_OP = "INS"
		DATA_OBJECT = "doMaterialSlip"
		REST_ENDPOINT = "itemSlips"
		RELATED_TABLE = 'LG_STFICHE'