# Generated by Django 3.0.1 on 2022-03-25 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rotated', models.BooleanField(db_index=True, default=False, verbose_name='Dosyaya yönlendirildi')),
                ('rotated_to', models.TextField(blank=True, null=True, verbose_name='Yönlendirilen dosya')),
                ('rotated_at', models.DateTimeField(blank=True, null=True, verbose_name='Yönlendirilme zamanı')),
                ('rotated_fields', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(default='default', max_length=50)),
                ('period', models.CharField(default='', max_length=10)),
                ('user', models.CharField(default='AKTARIM', max_length=32)),
                ('handler', models.CharField(db_index=True, max_length=6)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=24)),
                ('data', models.TextField(blank=True, null=True)),
                ('related_object', models.CharField(blank=True, max_length=50, null=True)),
                ('internal_ref', models.IntegerField(blank=True, null=True)),
                ('request', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('exception', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('error_code', models.SmallIntegerField(choices=[(1, 'Internal exception'), (2, 'Endpoint not responds'), (3, 'Malformed request')], db_index=True, default=0)),
                ('pid', models.CharField(db_index=True, max_length=32)),
                ('took', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('next_flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nextflow', to='bti.Flow')),
                ('prev_flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prevflow', to='bti.Flow')),
            ],
            options={
                'db_table': 'btix_flow',
            },
        ),
    ]
