# Generated by Django 3.0.1 on 2022-03-27 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bti', '0002_taskactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskactivity',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='taskactivity',
            table='btix_activity',
        ),
    ]
