# Generated by Django 3.0.1 on 2023-04-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bti', '0005_auto_20220402_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='keyword1',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flow',
            name='keyword2',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flow',
            name='keyword3',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
