version: '3.8'

services:
  londra_api:
    build: ./
    container_name: londra_api
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: /bin/sh entrypoint.sh
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file: 
      - ./.env.dev