# Generated by Django 3.2.12 on 2023-09-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0002_slipque_slipquelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storemap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmnr', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='FIRMNR', max_length=50)),
                ('store_nr', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='STORE_NR', max_length=50, null=True)),
                ('wh_nr', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='WH_NR', max_length=50, null=True)),
                ('store_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='STORE_NAME', max_length=150, null=True)),
                ('wh_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='WH_NAME', max_length=150, null=True)),
                ('status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='STATUS', max_length=50, null=True)),
                ('wh_demand_status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='WH_DEMAND_STATUS', max_length=50, null=True)),
                ('depoxnum', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DEPOXNUM', max_length=10, null=True)),
                ('transfer_status', models.IntegerField(blank=True, db_column='TRANSFER_STATUS', null=True)),
                ('arpcode', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ARPCODE', max_length=50, null=True)),
            ],
            options={
                'db_table': 'BTI_PRT_STOREMAP',
                'managed': False,
                'target_db': 'idea',
            },
        ),
    ]
