from datetime import datetime

from django.urls import path
from django.http import HttpResponse

from .views import (
    OrderView,
    PurchaseOrderCancellable,
    DispatchView,
    TransferRefundView,
    WantageView,
    InvoiceView,
    EmcenterView,
    ItemView,
    ItemCodesView,
    AccountView,
    PayPlanView,
    ARPView,
    SlipView
)

def test_view(request):
    return HttpResponse(f"Test! {datetime.now()}")


urlpatterns = [
    path(
        'purchaseorder/purchaseorder/purchaseorder',
        OrderView.as_view(),
        name='order_view'
    ),
    path(
        'purchaseorder/purchaseorder/purchaseorder/',
        OrderView.as_view(),
        name='order_view'
    ),
    path(
        'purchaseorder/purchaseorder/purchaseorder/param',
        OrderView.as_view(),
        name='order_view'
    ),
    path(
        'purchaseorder/purchaseorder/purchaseorder/param/',
        OrderView.as_view(),
        name='order_view'
    ),
    path(
        'purchaseorder/purchaseorder/purchaseorder/param/<str:param>',
        OrderView.as_view(),
        name='order_view'
    ),
    path(
        'purchaseorder/purchaseorder/purchaseorder/param/<str:param>/',
        OrderView.as_view(),
        name='order_view'
    ),
    path(
        'purchaseOrder/purchaseOrder/purchaseOrderCancellable',
        PurchaseOrderCancellable.as_view(),
        name='purchase_order_cancellable_view'
    ),
    path(
        'purchaseOrder/purchaseOrder/purchaseOrderCancellable/',
        PurchaseOrderCancellable.as_view(),
        name='purchase_order_cancellable_view'
    ),
    path(
        'purchaseDispatch/purchaseDispatch/purchaseDispatch',
        DispatchView.as_view(),
        name='dispatch_view'
    ),
    path(
        'purchaseDispatch/purchaseDispatch/purchaseDispatch/',
        DispatchView.as_view(),
        name='dispatch_view'
    ),
    path(
        'itemSlip/itemSlip/itemSlip',
        TransferRefundView.as_view(),
        name='transfer_refund_view'
    ),
    path(
        'itemSlip/itemSlip/itemSlip/',
        TransferRefundView.as_view(),
        name='transfer_refund_view'
    ),
    path(
        'itemSlip/itemSlip/wantage',
        WantageView.as_view(),
        name='wantage_view'
    ),
    path(
        'itemSlip/itemSlip/wantage/',
        WantageView.as_view(),
        name='wantage_view'
    ),
    path(
        'itemslip/itemslip/wantage',
        WantageView.as_view(),
        name='wantage_view'
    ),
    path(
        'itemslip/itemslip/wantage/',
        WantageView.as_view(),
        name='wantage_view'
    ),
    path(
        'salesInvoice/salesInvoice/salesInvoice',
        InvoiceView.as_view(),
        name='invoice_view'
    ),
    path(
        'salesInvoice/salesInvoice/salesInvoice/',
        InvoiceView.as_view(),
        name='invoice_view'
    ),
    path(
        'emccenter/emccenter/emccenter',
        EmcenterView.as_view(),
        name='emcenter_view'
    ),
    path(
        'emccenter/emccenter/emccenter/code/<str:code>',
        EmcenterView.as_view(),
        name='emcenter_view'
    ),
    path(
        'emccenter/emccenter/emccenter/code/<str:code>/',
        EmcenterView.as_view(),
        name='emcenter_view'
    ),
    path(
        'items/items/items',
        ItemView.as_view(),
        name='item_view'
    ),
    path(
        'items/items/items/',
        ItemView.as_view(),
        name='item_view'
    ),
    path(
        'items/items/items/code/<str:code>',
        ItemView.as_view(),
        name='item_view'
    ),
      path(
        'items/items/items/code/<str:code>/',
        ItemView.as_view(),
        name='item_view'
    ),
    path(
        'items/items/items/code/<str:code>/endDate/<str:end_date>',
        ItemView.as_view(),
        name='item_view'
    ),
    path(
        'items/items/items/code/<str:code>/endDate/<str:end_date>/',
        ItemView.as_view(),
        name='item_view'
    ),
    path(
        'items/items/itemscodelist',
        ItemCodesView.as_view(),
        name='itemcode_view'
    ),
    path(
        'items/items/itemscodelist/',
        ItemCodesView.as_view(),
        name='itemcode_view'
    ),
    path(
        'items/items/itemscodelist/code/<str:code>',
        ItemCodesView.as_view(),
        name='itemcode_view'
    ),
    path(
        'items/items/itemscodelist/code/<str:code>/',
        ItemCodesView.as_view(),
        name='itemcode_view'
    ),
    path(
        'items/items/itemscodelist/code/<str:code>/active/<int:active>',
        ItemCodesView.as_view(),
        name='itemcode_view'
    ),
    path(
        'items/items/itemscodelist/code/<str:code>/active/<int:active>/',
        ItemCodesView.as_view(),
        name='itemcode_view'
    ),
    path(
        'accountcode/accountcode',
        AccountView.as_view(),
        name='accountcode_view'
    ),
    path(
        'accountcode/accountcode/',
        AccountView.as_view(),
        name='accountcode_view'
    ),
    path(
        'accountcode/accountcode/code/<str:code>',
        AccountView.as_view(),
        name='accountcode_view'
    ),
    path(
        'accountcode/accountcode/code/<str:code>/',
        AccountView.as_view(),
        name='accountcode_view'
    ),
    path(
        'paymentplan/paymentplan',
        PayPlanView.as_view(),
        name='paymentplan_view'
    ),
    path(
        'paymentplan/paymentplan/',
        PayPlanView.as_view(),
        name='paymentplan_view'
    ),
    path(
        'paymentplan/paymentplan/code/<str:code>',
        PayPlanView.as_view(),
        name='paymentplan_view'
    ),
    path(
        'paymentplan/paymentplan/code/<str:code>/',
        PayPlanView.as_view(),
        name='paymentplan_view'
    ),
    path(
        'arpcard/arpcard/arpcard',
        ARPView.as_view(),
        name='arp_view'
    ),
    path(
        'arpcard/arpcard/arpcard/',
        ARPView.as_view(),
        name='arp_view'
    ),
    path(
        'arpcard/arpcard/arpcard/def',
        ARPView.as_view(),
        name='arp_view'
    ),
    path(
        'arpcard/arpcard/arpcard/def/',
        ARPView.as_view(),
        name='arp_view'
    ),
    path(
        'arpcard/arpcard/arpcard/def/<str:kind>',
        ARPView.as_view(),
        name='arp_view'
    ),
    path(
        'arpcard/arpcard/arpcard/def/<str:kind>/',
        ARPView.as_view(),
        name='arp_view'
    ),
     path(
        'slip/slipapi/slipapi/',
        SlipView.as_view(),
        name='slip_view'
    ),
     path(
        'items/items/itemsconsumable',
        ItemCodesView.as_view(),
        name='itemcode_view'
    ),
    path(
        'test',
        test_view,
        name='test'
    )
]
