# Generated by Django 3.2.12 on 2023-03-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotpos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotpos',
            name='last_synced',
            field=models.DateTimeField(null=True),
        ),
    ]
