"""
 Tüm hakları BTI Bilişim Danışmanlık ve Yazılım Şirketi adına saklıdır.
 
"""

import logging
from datetime import datetime, date

from django.core.management.base import BaseCommand, CommandError
from django.conf import settings
from django.apps import apps

logger = logging.getLogger("erp")

class Command(BaseCommand):
    help = "Test erp models"

    def handle(self, *a, **kw):
        models = []
        f = models.append
        from erp.models import (
            LG_EMUHACC,
            LG_ACCCODES,
            LG_CRDACREF,
            LG_EMFICHE,
            LG_LOGREP,
            LG_EMUHTOT,
            LG_EMFLINE,
            LG_ADDTAX,
            LG_ADDTAXLINE,
            LG_CSCARD,
            LG_CSROLL,
            LG_CSTRANS,
            LG_CLCARD,
            LG_CLFICHE,
            LG_CLINTEL,
            LG_CLTOTFIL,
            LG_CLRNUMS,
            LG_CLFLINE,
            LG_FOLDER,
            LG_EMGRPASS,
            LG_EMPGROUP,
            LG_EMPLOYEE,
            LG_ENGCLINE,
            LG_FIRMDOC,
            LG_LABORREQ,
            LG_LNGEXCSETS,
            LG_TRANSAC,
            LG_PRDCOST,
            LG_PROJECT,
            LG_SHIPINFO,
            LG_TRGPAR,
            LG_SELCHVAL,
            LG_ITMBOMAS,
            LG_ITMCLSAS,
            LG_STINVTOT,
            LG_ITMFACTP,
            LG_INVDEF,
            LG_CHARASGN,
            LG_CHARCODE,
            LG_CHARVAL,
            LG_ITEMS,
            LG_ITEMSUBS,
            LG_SERILOTN,
            LG_SLTRANS,
            LG_STCOMPLN,
            LG_STINVENS,
            LG_SUPPASGN,
            LG_ITMUNITA,
            LG_ACTIVITYAMNT,
            LG_WSGRPF,
            LG_WSGRPASS,
            LG_PRVOPASG,
            LG_PRODORD,
            LG_PEGGING,
            LG_BOMASTER,
            LG_BOMLINE,
            LG_BOMPARAM,
            LG_COPRDBOM,
            LG_ROUTING,
            LG_RTNGLINE,
            LG_DISPLINE,
            LG_WORKSTAT,
            LG_WSATTASG,
            LG_WSATTVAS,
            LG_WSCHCODE,
            LG_WSCHVAL,
            LG_QASGN,
            LG_QCLVAL,
            LG_SLQCASGN,
            LG_QCSET,
            LG_QCSLINE,
            LG_CONTACTS,
            LG_DISTLINE,
            LG_DISTTEMP,
            LG_LNOPASGN,
            LG_LOCATION,
            LG_OPERTION,
            LG_OPRTREQ,
            LG_OPATTASG,
            LG_ACTPEPL,
            LG_ROUTETRS,
            LG_ROUTE,
            LG_SLSMAN,
            LG_SLSCLREL,
            LG_TARGETS,
            LG_TOOLREQ,
            LG_STFICHE,
            LG_INVOICE,
            LG_SRVTOT,
            LG_ORFICHE,
            LG_ORFLINE,
            LG_PRODUCER,
            LG_STLINE,
            LG_SRVNUMS,
            L_COUNTRY,
            L_CITY,
            L_TOWN,
            L_DISTRICT,
            L_POSTCODE,
            L_BANKCODE,
            L_BNBRANCH,
            LG_CATEGLISTS,
            L_CURRENCYLIST,
            L_CURRENCYPARS,
            L_CAPIDEPT,
            L_CAPIDIV,
            L_LDOCNUM,
            L_DAILYEXCHANGES,
            L_CAPIFACTORY,
            L_CAPIFACTDIV,
            L_CAPIFIRM,
            L_FIRMPARAMS,
            L_CAPIGROUP,
            LG_HISTORY,
            L_CAPIUSER,
            L_GOUSERS,
            L_NET,
            L_CAPIPERIOD,
            L_DYNREP,
            L_DYNREPUSRR,
            L_CAPIROLE,
            L_SHPAGENT,
            L_SHPTYPES,
            LG_USAGESTAT,
            L_STATUSINFO,
            L_CAPITERMINAL,
            L_TRADGRP,
            L_CAPIUNIT,
            L_CAPIVERS,
            L_CAPIWHOUSE,
            LG_ASCOND,
            LG_DECARDS,
            LG_DEMANDFICHE,
            LG_DEMANDLINE,
            LG_DEMANDPEGGING,
            LG_EMCENTER,
            LG_PAYLINES,
            LG_PAYPLANS,
            LG_PRCARDS,
            LG_PRCLIST,
            LG_PAYTRANS,
            LG_SPECODES,
            LG_SRVCARD,
            LG_UNITSETF,
            LG_UNITSETL,
            LG_SRVUNITA,
            LG_UNITSETC,
            LG_WFTASK,
            LG_FAREGIST,
            LG_FAYEAR,
            LG_BANKACC,
            LG_BNCARD,
            LG_BNFICHE,
            LG_BNTOTFIL,
            LG_BNFLINE,
            LG_KSCARD,
            LG_CSHTOTS,
            LG_KSLINES,
            LG_CAMPAIGN,
            LG_EARCHIVEDET,
        )
        print('hi!')
        f(LG_EMUHACC)
        f(LG_ACCCODES)
        f(LG_CRDACREF)
        f(LG_EMFICHE)
        f(LG_LOGREP)
        f(LG_EMUHTOT)
        f(LG_EMFLINE)
        f(LG_ADDTAX)
        f(LG_ADDTAXLINE)
        f(LG_CSCARD)
        f(LG_CSROLL)
        f(LG_CSTRANS)
        f(LG_CLCARD)
        f(LG_CLFICHE)
        f(LG_CLINTEL)
        f(LG_CLTOTFIL)
        f(LG_CLRNUMS)
        f(LG_CLFLINE)
        f(LG_FOLDER)
        f(LG_EMGRPASS)
        f(LG_EMPGROUP)
        f(LG_EMPLOYEE)
        f(LG_ENGCLINE)
        f(LG_FIRMDOC)
        f(LG_LABORREQ)
        f(LG_LNGEXCSETS)
        f(LG_TRANSAC)
        f(LG_PRDCOST)
        f(LG_PROJECT)
        f(LG_SHIPINFO)
        f(LG_TRGPAR)
        f(LG_SELCHVAL)
        f(LG_ITMBOMAS)
        f(LG_ITMCLSAS)
        f(LG_STINVTOT)
        f(LG_ITMFACTP)
        f(LG_INVDEF)
        f(LG_CHARASGN)
        f(LG_CHARCODE)
        f(LG_CHARVAL)
        f(LG_ITEMS)
        f(LG_ITEMSUBS)
        f(LG_SERILOTN)
        f(LG_SLTRANS)
        f(LG_STCOMPLN)
        f(LG_STINVENS)
        f(LG_SUPPASGN)
        f(LG_ITMUNITA)
        f(LG_ACTIVITYAMNT)
        f(LG_WSGRPF)
        f(LG_WSGRPASS)
        f(LG_PRVOPASG)
        f(LG_PRODORD)
        f(LG_PEGGING)
        f(LG_BOMASTER)
        f(LG_BOMLINE)
        f(LG_BOMPARAM)
        f(LG_COPRDBOM)
        f(LG_ROUTING)
        f(LG_RTNGLINE)
        f(LG_DISPLINE)
        f(LG_WORKSTAT)
        f(LG_WSATTASG)
        f(LG_WSATTVAS)
        f(LG_WSCHCODE)
        f(LG_WSCHVAL)
        f(LG_QASGN)
        f(LG_QCLVAL)
        f(LG_SLQCASGN)
        f(LG_QCSET)
        f(LG_QCSLINE)
        f(LG_CONTACTS)
        f(LG_DISTLINE)
        f(LG_DISTTEMP)
        f(LG_LNOPASGN)
        f(LG_LOCATION)
        f(LG_OPERTION)
        f(LG_OPRTREQ)
        f(LG_OPATTASG)
        f(LG_ACTPEPL)
        f(LG_ROUTETRS)
        f(LG_ROUTE)
        f(LG_SLSMAN)
        f(LG_SLSCLREL)
        f(LG_TARGETS)
        f(LG_TOOLREQ)
        f(LG_STFICHE)
        f(LG_INVOICE)
        f(LG_SRVTOT)
        f(LG_ORFICHE)
        f(LG_ORFLINE)
        f(LG_PRODUCER)
        f(LG_STLINE)
        f(LG_SRVNUMS)
        f(L_COUNTRY)
        f(L_CITY)
        f(L_TOWN)
        f(L_DISTRICT)
        f(L_POSTCODE)
        f(L_BANKCODE)
        f(L_BNBRANCH)
        f(LG_CATEGLISTS)
        f(L_CURRENCYLIST)
        f(L_CURRENCYPARS)
        f(L_CAPIDEPT)
        f(L_CAPIDIV)
        f(L_LDOCNUM)
        f(L_DAILYEXCHANGES)
        f(L_CAPIFACTORY)
        f(L_CAPIFACTDIV)
        f(L_CAPIFIRM)
        f(L_FIRMPARAMS)
        f(L_CAPIGROUP)
        f(LG_HISTORY)
        f(L_CAPIUSER)
        f(L_GOUSERS)
        f(L_NET)
        f(L_CAPIPERIOD)
        f(L_DYNREP)
        f(L_DYNREPUSRR)
        f(L_CAPIROLE)
        f(L_SHPAGENT)
        f(L_SHPTYPES)
        f(LG_USAGESTAT)
        f(L_STATUSINFO)
        f(L_CAPITERMINAL)
        f(L_TRADGRP)
        f(L_CAPIUNIT)
        f(L_CAPIVERS)
        f(L_CAPIWHOUSE)
        f(LG_ASCOND)
        f(LG_DECARDS)
        f(LG_DEMANDFICHE)
        f(LG_DEMANDLINE)
        f(LG_DEMANDPEGGING)
        f(LG_EMCENTER)
        f(LG_PAYLINES)
        f(LG_PAYPLANS)
        f(LG_PRCARDS)
        f(LG_PRCLIST)
        f(LG_PAYTRANS)
        f(LG_SPECODES)
        f(LG_SRVCARD)
        f(LG_UNITSETF)
        f(LG_UNITSETL)
        f(LG_SRVUNITA)
        f(LG_UNITSETC)
        f(LG_WFTASK)
        f(LG_FAREGIST)
        f(LG_FAYEAR)
        f(LG_BANKACC)
        f(LG_BNCARD)
        f(LG_BNFICHE)
        f(LG_BNTOTFIL)
        f(LG_BNFLINE)
        f(LG_KSCARD)
        f(LG_CSHTOTS)
        f(LG_KSLINES)
        f(LG_CAMPAIGN)
        f(LG_EARCHIVEDET)


        total = 0
        for (i, model) in enumerate(models):
            print(i+1, model._meta, ">", model._meta.db_table)
            c = model.objects.filter().count()
            print(c, model.objects.filter()[0:1])
            print("-"*3)
            total += c

        print(f"Total recs: {total}")
