version: '3.8'

services:
  moneypay_api:
    build: ./
    container_name: moneypay_api
    command: gunicorn --workers=5 --threads=2 common.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file: 
      - ./.env.prod
