"""
 Tüm hakları BTI Bilişim Danışmanlık ve Yazılım Şirketi adına saklıdır.
 
"""

from erp.integration import base

class AssetRecordYearlyLocal(base.BaseSerialiazer):
	TABLE_TYPE = base.IntegerField(label="Tablo Türü", table="LG_FAYEAR",field="TABLETY",required=False)
	FREGREF = base.IntegerField(label="Sabit kıymet kayıt referansı", table="LG_FAYEAR",field="FREGREF",required=False)
	YEAR = base.IntegerField(label="Yıl", table="LG_FAYEAR",field="YEAR",required=False)
	DEPR_RATE = base.FloatField(label="Amortisman oranı", table="LG_FAYEAR",field="DRATE",required=False)
	REVAL_RATE = base.FloatField(label="Değerleme Oranı", table="LG_FAYEAR",field="REVRATE",required=False)
	DEPR_TYPE = base.IntegerField(label="Amortisman türü (1:Normal-2: Azalan Bakiyeler", table="LG_FAYEAR",field="DTYPE",min_value=0, max_value=1,required=False)
	QUANTITY_OUT = base.FloatField(label="Decreased Quantity", table="LG_FAYEAR",field="QUANOUT",required=False)
	LC_INIT_COST = base.FloatField(label="Start Numbers For Local Currency", table="LG_FAYEAR",field="LOCFIGS_COSTOP",required=False)
	LC_EXPENSES = base.FloatField(label="Yerel para birimi üzerinden değerlemeye tabi giderler", table="LG_FAYEAR",field="LOCFIGS_EXPUSUAL",required=False)
	LC_EXPENSES_EXCLRV = base.FloatField(label="Yerel para birimi üzerinden değerleme harici giderler", table="LG_FAYEAR",field="LOCFIGS_EXPOUTREV",required=False)
	LC_CUMEXPEN_EXCLRV = base.FloatField(label="Accumulated Expenses Not Revaluated For Local", table="LG_FAYEAR",field="LOCFIGS_CUMEXPOR",required=False)
	LC_AMOUNT_OUT = base.FloatField(label="Decreased Value For Local Currency", table="LG_FAYEAR",field="LOCFIGS_AMOUNTOUT",required=False)
	LC_AMOUNT_EXCLRV = base.FloatField(label="Decreased Amount Not Revaluated For Local", table="LG_FAYEAR",field="LOCFIGS_AMOUNTOUTR",required=False)
	LC_BOOKVAL_OPEN = base.FloatField(label="Yerel para birimi üzerinden değerleme öncesi sabit kıymet değeri", table="LG_FAYEAR",field="LOCFIGS_BOOKVALOP",required=False)
	LC_ACCDEPR_OPEN = base.FloatField(label="Yerel para birimi üzerinden değerleme öncesi birikmiş amortisman", table="LG_FAYEAR",field="LOCFIGS_BOOKVALOP",required=False)
	LC_ACCDEPR_OUT = base.FloatField(label="Amount That Will Be Decreased From Accumulated", table="LG_FAYEAR",field="LOCFIGS_ACCDPOUT",required=False)
	LC_BOOKVAL_REVD = base.FloatField(label="Yerel para birimi üzerinden değerleme sonrası sabit kıymet değeri", table="LG_FAYEAR",field="LOCFIGS_BOOKVALRV",required=False)
	LC_ACCDEPR_REVD = base.FloatField(label="Yerel para birimi üzerinden değerleme sonrası birikmiş amortisman", table="LG_FAYEAR",field="LOCFIGS_ACCDEPRRV",required=False)
	LC_ANNDEPR = base.FloatField(label="Yerel para birimi üzerinden yıllık amortisman tutarı", table="LG_FAYEAR",field="LOCFIGS_DEPRANN",required=False)
	LC_ACCDEPR_YREND = base.FloatField(label="End Of Year Accumulated Depreciation For Local Currency", table="LG_FAYEAR",field="LOCFIGS_ACCDEPRCST",required=False)
	FC_INIT_COST = base.FloatField(label="Rap. dövizi başlangıç numaraları", table="LG_FAYEAR",field="CURFIGS_COSTOP",required=False)
	FC_EXPENSES = base.FloatField(label="Rap. dövizi değerlemeye tabi giderler", table="LG_FAYEAR",field="CURFIGS_EXPUSUAL",required=False)
	FC_EXPENSES_EXCLRV = base.FloatField(label="Rap. dövizi değerleme harici giderler", table="LG_FAYEAR",field="CURFIGS_EXPOUTREV",required=False)
	FC_CUMEXPEN_EXCLRV = base.FloatField(label="Rap. Dövizi değerleme harici birikmiş giderler", table="LG_FAYEAR",field="CURFIGS_CUMEXPOR",required=False)
	FC_AMOUNT_OUT = base.FloatField(label="Decreased Value For Reporting Currency", table="LG_FAYEAR",field="CURFIGS_AMOUNTOUT",required=False)
	FC_AMOUNT_EXCLRV = base.FloatField(label="Decreased Amount Not Revaluated For Reporting Currency", table="LG_FAYEAR",field="CURFIGS_AMOUNTOUTR",required=False)
	FC_BOOKVAL_OPEN = base.FloatField(label="Rap. Dövizi üzerinden değerleme öncesi sabit kıymet değeri", table="LG_FAYEAR",field="CURFIGS_BOOKVALOP",required=False)
	FC_ACCDEPR_OPEN = base.FloatField(label="Rap. Dövizi üzerinden değerleme öncesi birikmiş amortisman", table="LG_FAYEAR",field="CURFIGS_ACCDPOUT",required=False)
	FC_BOOKVAL_REVD = base.FloatField(label="Rap. Dövizi üzerinden değerleme sonrası sabit kıymet değeri", table="LG_FAYEAR",field="CURFIGS_BOOKVALRV",required=False)
	FC_ACCDEPR_REVD = base.FloatField(label="Rap. Dövizi üzerinden değerleme sonrası birikmiş amortisman", table="LG_FAYEAR",field="CURFIGS_ACCDEPRRV",required=False)
	FC_ANNDEPR = base.FloatField(label="Rap. Dövizi üzerinden yıllık amortisman tutarı", table="LG_FAYEAR",field="CURFIGS_DEPRANN",required=False)
	FC_ACCDEPR_YREND = base.FloatField(label="End Of Year Accumulated Depreciation For Reporting Currency", table="LG_FAYEAR",field="CURFIGS_ACCDEPREOY",required=False)
	FC_ACCDEPR_INCOST = base.FloatField(label="Accumulated Depreciation For Cost For Reporting Currency", table="LG_FAYEAR",field="CURFIGS_ACCDEPRCST",required=False)
	VAT_DEDUCTED = base.FloatField(label="VAT That Posted to General Ledger", table="LG_FAYEAR",field="VATPOSTED",required=False)
	DEPR_POSTED = base.IntegerField(label="Depreciation Posted Flag (1- Evet, 0- Hayır)", table="LG_FAYEAR",field="DACCFLAG",min_value=0, max_value=1,required=False)
	REVAL_POSTED = base.IntegerField(label="Revaluation Posted Flag", table="LG_FAYEAR",field="RACCFLAG",min_value=0, max_value=1,required=False)
	VAT_POSTED = base.IntegerField(label="VAT Posted Flag", table="LG_FAYEAR",field="VACCFLAG",min_value=0, max_value=1,required=False)
	MONTH_CALC = base.IntegerField(label="Calculated End Of Period", table="LG_FAYEAR",field="CALCMON",required=False)

class AssetRecordYearlyFC(base.BaseSerialiazer):
	TABLE_TYPE = base.IntegerField(label="Tablo Türü", table="LG_FAYEAR",field="TABLETY",required=False)
	FREGREF = base.IntegerField(label="Sabit kıymet kayıt referansı", table="LG_FAYEAR",field="FREGREF",required=False)
	YEAR = base.IntegerField(label="Yıl", table="LG_FAYEAR",field="YEAR",required=False)
	DEPR_RATE = base.FloatField(label="Amortisman Oranı", table="LG_FAYEAR",field="DRATE",required=False)
	REVAL_RATE = base.FloatField(label="Değerleme Oranı", table="LG_FAYEAR",field="REVRATE",required=False)
	DEPR_TYPE = base.IntegerField(label="Amortisman türü (1:Normal-2: Azalan Bakiyeler", table="LG_FAYEAR",field="DTYPE",min_value=0, max_value=1,required=False)
	QUANTITY_OUT = base.FloatField(label="Decreased Quantity", table="LG_FAYEAR",field="QUANOUT",required=False)
	LC_INIT_COST = base.FloatField(label="Yerel para birimi başlangıç numaraları", table="LG_FAYEAR",field="LOCFIGS_COSTOP",required=False)
	LC_EXPENSES = base.FloatField(label="Yerel para birimi üzerinden değerlemeye tabi giderler", table="LG_FAYEAR",field="LOCFIGS_EXPUSUAL",required=False)
	LC_EXPENSES_EXCLRV = base.FloatField(label="Yerel para birimi üzerinden değerleme harici giderler", table="LG_FAYEAR",field="LOCFIGS_EXPOUTREV",required=False)
	LC_CUMEXPEN_EXCLRV = base.FloatField(label="Accumulated Expenses Not Revaluated For Local Currency", table="LG_FAYEAR",field="LOCFIGS_CUMEXPOR",required=False)
	LC_AMOUNT_OUT = base.FloatField(label="Decreased Value For Local Currency", table="LG_FAYEAR",field="LOCFIGS_AMOUNTOUT",required=False)
	LC_AMNOUT_EXCLRV = base.FloatField(label="Decreased Amount Not Revaluated For Local Currency", table="LG_FAYEAR",field="LOCFIGS_AMOUNTOUTR",required=False)
	LC_BOOKVAL_OPEN = base.FloatField(label="Yerel para birimi üzerinden değerleme öncesi sabit kıymet değeri", table="LG_FAYEAR",field="LOCFIGS_BOOKVALOP",required=False)
	LC_ACCDEPR_OPEN = base.FloatField(label="Yerel para birimi üzerinden değerleme öncesi birikmiş amortisman", table="LG_FAYEAR",field="LOCFIGS_ACCDEPROP",required=False)
	LC_ACCDEPR_OUT = base.FloatField(label="Amount That Will Be Decreased From Accumulated Depreciation for local currency", table="LG_FAYEAR",field="LOCFIGS_ACCDPOUT",required=False)
	LC_BOOKVAL_REVD = base.FloatField(label="Yerel para birimi üzerinden değerleme sonrası sabit kıymet değeri", table="LG_FAYEAR",field="LOCFIGS_BOOKVALRV",required=False)
	LC_ACCDEPR_REVD = base.FloatField(label="Yerel para birimi üzerinden değerleme sonrası birikmiş amortisman", table="LG_FAYEAR",field="LOCFIGS_ACCDEPRRV",required=False)
	LC_ANNDEPR = base.FloatField(label="Yerel para birimi üzerinden yıllık amortisman tutarı", table="LG_FAYEAR",field="LOCFIGS_DEPRANN",required=False)
	LC_ACCDEPR_YREND = base.FloatField(label="End Of Year Accumulated Depreciation For Local Currency", table="LG_FAYEAR",field="LOCFIGS_ACCDEPREOY",required=False)
	LC_ACCDEPR_INCOST = base.FloatField(label="Accumulated Depreciation For Cost For Local Currency", table="LG_FAYEAR",field="LOCFIGS_ACCDEPREOY",required=False)
	FC_INIT_COST = base.FloatField(label="Rap. dövizi üzerinden başlangıç numaraları", table="LG_FAYEAR",field="CURFIGS_COSTOP",required=False)
	FC_EXPENSES = base.FloatField(label="Rap. dövizi üzerinden değerlemeye tabi giderler", table="LG_FAYEAR",field="CURFIGS_EXPUSUAL",required=False)
	FC_EXPENSES_EXCLRV = base.FloatField(label="Rap. dövizi üzerinden değerleme harici giderler", table="LG_FAYEAR",field="CURFIGS_EXPOUTREV",required=False)
	FC_CUMEXPEN_EXCLRV = base.FloatField(label="Rap. Dövizi üzerinden değerleme harici birikmiş giderler", table="LG_FAYEAR",field="CURFIGS_CUMEXPOR",required=False)
	FC_AMOUNT_EXCLRV = base.FloatField(label="Decreased Amount Not Revaluated For Reporting Currency", table="LG_FAYEAR",field="CURFIGS_AMOUNTOUTR",required=False)
	FC_BOOKVAL_OPEN = base.FloatField(label="Rap. Dövizi üzerinden değerleme öncesi sabit kıymet değeri", table="LG_FAYEAR",field="CURFIGS_BOOKVALOP",required=False)
	FC_ACCDEPR_OPEN = base.FloatField(label="Rap. Dövizi üzerinden değerleme öncesi birikmiş amortisman", table="LG_FAYEAR",field="CURFIGS_ACCDEPROP",required=False)
	FC_ACCDEPR_OUT = base.FloatField(label="Amount That Will Be Decreased From Accumulated Depreciation For Reporting Currency", table="LG_FAYEAR",field="CURFIGS_ACCDPOUT",required=False)
	FC_BOOKVAL_REVD = base.FloatField(label="Rap. Dövizi üzerinden değerleme sonrası sabit kıymet değeri", table="LG_FAYEAR",field="CURFIGS_BOOKVALRV",required=False)
	FC_ACCDEPR_REVD = base.FloatField(label="Rap. Dövizi üzerinden değerleme sonrası birikmiş amortisman", table="LG_FAYEAR",field="CURFIGS_ACCDEPRRV",required=False)
	FC_ACCDEPR_YREND = base.FloatField(label="End Of Year Accumulated Depreciation For Reporting Currency", table="LG_FAYEAR",field="CURFIGS_ACCDEPREOY",required=False)
	FC_ACCDEPR_INCOST = base.FloatField(label="Accumulated Depreciation For Cost For Reporting Currency", table="LG_FAYEAR",field="CURFIGS_ACCDEPRCST",required=False)
	VAT_DEDUCTED = base.FloatField(label="VAT That Posted to General Ledger", table="LG_FAYEAR",field="VATPOSTED",required=False)
	DEPR_POSTED = base.IntegerField(label="Depreciation Posted Flag (1- Evet, 0- Hayır)", table="LG_FAYEAR",field="DACCFLAG",min_value=0, max_value=1,required=False)
	REVAL_POSTED = base.IntegerField(label="Revaluation Posted Flag", table="LG_FAYEAR",field="RACCFLAG",min_value=0, max_value=1,required=False)
	VAT_POSTED = base.IntegerField(label="VAT Posted Flag", table="LG_FAYEAR",field="VACCFLAG",min_value=0, max_value=1,required=False)
	MONTH_CALC = base.IntegerField(label="Calculated End Of Period", table="LG_FAYEAR",field="CALCMON",required=False)
	DATE_DEPRSTART2 = base.IntegerField(label="Amortisman Başlangıcı", table="LG_FAREGIST",field="DATEOFDEPR",required=False)
	PART_DEP2 = base.IntegerField(label="Kıst Amortismanı", table="LG_FAREGIST",field="PARTDEP2",min_value=0, max_value=1,required=False)


class AssetRecord(base.Serializer):
	"""
		Sabit kıymet kaydı
	"""
	class Meta:
		XML_ROOT = 'FIXED_ASSET_REGISTRY'
		XML_SUBROOT = 'FIXED_ASSET_REGISTRY'
		DATA_OBJECT = 'doFARegistry'
		REST_ENDPOINT = 'FARegistries'
		RELATED_TABLE = 'LG_FAREGIST'

	CODE = base.CharField(label="Kod", table="LG_FAREGIST",field="REGCODE",max_length=17,required=False)
	DIVISION = base.IntegerField(label="İşyeri", table="LG_FAREGIST",field="BRANCH",required=False)
	DEPARTMENT = base.IntegerField(label="Bölüm", table="LG_FAREGIST",field="DEPARTMENT",required=False)
	TRANSFER = base.IntegerField(label="Devir / Yeni Kayıt", table="LG_FAREGIST",field="TRANSFER",min_value=0, max_value=1,required=False)
	ITEM_CODE = base.CharField(label="Malzeme Kodu", table="LG_ITEMS",field="CODE",max_length=25,required=False)
	DATE_ACQUIRED = base.IntegerField(label="Alım tarihi", table="LG_FAREGIST",field="DATEIN",required=True)
	DATE_DEPRSTART = base.IntegerField(label="Amortisman Başlangıcı", table="LG_FAREGIST",field="DATEOFDEPR",required=True)
	QUANTITY = base.FloatField(label="Miktar", table="LG_FAREGIST",field="QUANTITY",required=True)
	QUANTITY_OUT = base.FloatField(label="Decreased Quantity", table="LG_FAREGIST",field="TOTOUT",required=False)
	ACQ_VALUE = base.FloatField(label="Giriş Maliyeti", table="LG_FAREGIST",field="INVALUE",required=False)
	VAT_POST_DUR = base.IntegerField(label="KDV Süresi", table="LG_FAREGIST",field="VATDUR",required=False)
	DEPR_RATE = base.FloatField(label="Amortisman Oranı", table="LG_FAREGIST",field="DEPRRATE",required=True)
	DEPR_DUR = base.IntegerField(label="Amortisman Süresi", table="LG_FAREGIST",field="DEPRDUR",required=True)
	DEPR_TYPE = base.IntegerField(label="Amortisman türü", table="LG_FAREGIST",field="DEPRTYPE",min_value=0, max_value=1,required=True)
	REVALUATE = base.IntegerField(label="Değerleme işareti", table="LG_FAREGIST",field="REVFLAG",min_value=0, max_value=1,required=True)
	REV_DEPR = base.IntegerField(label="Değerleme amortismanı işareti", table="LG_FAREGIST",field="REVDEPFLAG",min_value=0, max_value=1,required=True)
	PARTIAL_DEPR = base.IntegerField(label="Kıst amortismanı", table="LG_FAREGIST",field="PARTDEP",min_value=0, max_value=1,required=True)
	CANCELLED = base.IntegerField(label="İptal edilmiş", table="LG_FAREGIST",field="CANCELLED",min_value=0, max_value=1,required=False)
	RC_XRATE = base.FloatField(label="Raporlama dövizi kuru", table="LG_FAREGIST",field="REPORTRATE",required=False)
	RC_ACQ_VALUE = base.FloatField(label="Giriş maliyeti", table="LG_FAREGIST",field="INVALUEX",required=False)
	TOTAL_EXPENSES = base.FloatField(label="Toplam masraflar", table="LG_FAREGIST",field="EXPTOTAL",required=False)
	ACCUM_DEPR = base.FloatField(label="Toplam amortisman", table="LG_FAREGIST",field="ACCUMDEPR",required=False)
	ACCUM_REVAL = base.FloatField(label="Total Revaluation", table="LG_FAREGIST",field="ACCUMREVAL",required=False)
	RC_TOTAL_EXPN = base.FloatField(label="Toplam gider (Raporlama Dövizi)", table="LG_FAREGIST",field="EXPTOTALX",required=False)
	RC_ACCUM_DEPR = base.FloatField(label="Birikmiş amortisman (Raporlama Dövizi)", table="LG_FAREGIST",field="ACCUMDEPRX",required=False)
	RC_ACCUM_REVAL = base.FloatField(label="Yeniden değerleme (Raporlama Dövizi)", table="LG_FAREGIST",field="ACCUMREVALX",required=False)
	DEPR_TYPE2 = base.IntegerField(label="Alternatif amortisman türü", table="LG_FAREGIST",field="DEPRTYPE2",required=False)
	DEPR_RATE2 = base.FloatField(label="Alternatif amortisman oranı", table="LG_FAREGIST",field="DEPRRATE2",required=False)
	DEPR_DUR2 = base.IntegerField(label="Alternatif amortisman periyodu", table="LG_FAREGIST",field="DEPRDUR2",required=False)
	REVALUATE2 = base.IntegerField(label="Alternative Revaluation Flag", table="LG_FAREGIST",field="REVALFLAG2",min_value=0, max_value=1,required=False)
	REV_DEPR2 = base.IntegerField(label="Alternative Revaluation Depreciation Flag", table="LG_FAREGIST",field="REVDEPRFLAG2",min_value=0, max_value=1,required=False)
	OPEN_REVAL = base.FloatField(label="Registered Fixed Asset Revaluation", table="LG_FAREGIST",field="BEGREVAL",required=False)
	OPEN_DEPR = base.FloatField(label="Registered Fixed Asset Depreciation", table="LG_FAREGIST",field="BEGDEPR",required=False)
	OPEN_REVDEPR = base.FloatField(label="Registered Fixed Asset Revaluation Depreciation", table="LG_FAREGIST",field="BEGREVDEPR",required=False)
	RC_OPENREV = base.FloatField(label="Registered Fixed Asset Revalution (Reporting Currency)", table="LG_FAREGIST",field="BEGREVALX",required=False)
	RC_OPENDEPR = base.FloatField(label="Registered Fixed Asset Depreciation (Reporting Currency)", table="LG_FAREGIST",field="BEGDEPRX",required=False)
	RC_OPENREVDEPR = base.FloatField(label="Registered Fixed Asset Revalution Depreciation", table="LG_FAREGIST",field="BEGREVDEPRX",required=False)
	OPEN_REVAL2 = base.FloatField(label="Registered Fixed Asset Revaluation (At Opening)", table="LG_FAREGIST",field="OPVALS_BEGREVAL",required=False)
	OPEN_DEPR2 = base.FloatField(label="Registered Fixed Asset Depreciation (At Opening)", table="LG_FAREGIST",field="OPVALS_BEGDEPR",required=False)
	OPEN_REVDEPR2 = base.FloatField(label="Registered Fixed Asset Revaluation Depreciation (At opening)", table="LG_FAREGIST",field="OPVALS_BEGREVDEPR",required=False)

	# subs
	YEARLY_LOCAL = base.serializers.ListSerializer(child=AssetRecordYearlyLocal())
	YEARLY_FC = base.serializers.ListSerializer(child=AssetRecordYearlyFC())
