# Generated by Django 4.2 on 2023-08-03 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(help_text='organizasyon id ', max_length=250)),
                ('unique_id', models.CharField(default='', help_text='kullanıcı TC No', max_length=50)),
                ('tarnet_user_id', models.CharField(help_text='armon api den gelen personel id', max_length=250)),
                ('direction', models.CharField(blank=True, help_text='1 ise giriş 2 ise çıkış', max_length=5, null=True)),
                ('full_name', models.CharField(max_length=150)),
                ('utc', models.DateTimeField()),
                ('in_time', models.DateTimeField(blank=True, null=True)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'employee_log',
            },
        ),
        migrations.CreateModel(
            name='LogoApiErrors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(blank=True, help_text='organizasyon id ', max_length=250, null=True)),
                ('unique_id', models.CharField(default='', help_text='kullanıcı TC No', max_length=50)),
                ('full_name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('message', models.CharField(blank=True, max_length=350, null=True)),
                ('msg_list', models.TextField(blank=True, help_text='logo dan gelen msg_list', null=True)),
                ('query_text', models.TextField(blank=True, help_text='logo ya iletilecek query text', null=True)),
                ('code', models.CharField(blank=True, help_text='logo daki personel kodu', max_length=250, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('date_time', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'logo_api_error',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(help_text='organizasyon id ', max_length=250, unique=True)),
                ('organization_name', models.CharField(help_text='Organizasyon Adı', max_length=250)),
                ('grant_type_id', models.CharField(blank=True, help_text='grant type id', max_length=250, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='app.organization')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_org', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_user',
            },
        ),
    ]
