# Generated by Django 3.0.1 on 2021-11-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=65)),
                ('is_success', models.BooleanField(db_index=True)),
                ('params', models.TextField(blank=True, null=True)),
                ('exception', models.TextField(blank=True, null=True)),
                ('took', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='operationdetail',
            options={'ordering': ['pk']},
        ),
    ]
