# Generated by Django 3.0.1 on 2021-11-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0003_invoiceque_invoicequelog_opque_opquelog_requestque_requestquelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestQue',
        ),
    ]
