# Generated by Django 3.0.1 on 2021-12-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0004_delete_requestque'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestQue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rotated', models.BooleanField(db_index=True, default=False, verbose_name='Dosyaya yönlendirildi')),
                ('rotated_to', models.TextField(blank=True, null=True, verbose_name='Yönlendirilen dosya')),
                ('rotated_at', models.DateTimeField(blank=True, null=True, verbose_name='Yönlendirilme zamanı')),
                ('rotated_fields', models.CharField(blank=True, max_length=255, null=True)),
                ('firm', models.CharField(max_length=60)),
                ('identifier', models.CharField(max_length=128, unique=True)),
                ('data', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('is_cancelled', models.BooleanField(db_index=True, default=False)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('processed', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'unique_together': {('firm', 'identifier')},
            },
        ),
        migrations.DeleteModel(
            name='RequestQueLog',
        ),
    ]
