# Generated by Django 3.0.1 on 2021-12-23 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0005_auto_20211222_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opque',
            old_name='op',
            new_name='op_code',
        ),
        migrations.AddField(
            model_name='opque',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='opque',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='opque',
            name='commission_amount',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='opque',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opque',
            name='district',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='opque',
            name='gsm',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='opque',
            name='mernis',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='opque',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='opque',
            name='pid',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opque',
            name='surname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='opque',
            name='taxnr',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='opque',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='opque',
            name='uid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='opque',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
