# Generated by Django 3.0.1 on 2021-12-23 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0006_auto_20211223_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opque',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='opque',
            name='city',
        ),
        migrations.RemoveField(
            model_name='opque',
            name='commission_amount',
        ),
        migrations.RemoveField(
            model_name='opque',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='opque',
            name='district',
        ),
        migrations.RemoveField(
            model_name='opque',
            name='gsm',
        ),
        migrations.RemoveField(
            model_name='opque',
            name='mernis',
        ),
        migrations.RemoveField(
            model_name='opque',
            name='name',
        ),
        migrations.RemoveField(
            model_name='opque',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='opque',
            name='taxnr',
        ),
        migrations.RemoveField(
            model_name='opque',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='opque',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='opque',
            name='zipcode',
        ),
    ]
