# Generated by Django 3.0.1 on 2021-12-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0007_auto_20211223_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='opque',
            name='commission_amount',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
