# Generated by Django 3.0.1 on 2021-12-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0008_opque_commission_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opque',
            name='pid',
        ),
    ]
