# Generated by Django 3.0.1 on 2021-12-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0009_remove_opque_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceque',
            name='day',
        ),
    ]
