# Generated by Django 3.0.1 on 2021-12-27 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bti', '0001_initial'),
        ('app_v1', '0011_auto_20211226_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceque',
            name='flow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bti.Flow'),
        ),
        migrations.AddField(
            model_name='invoiceque',
            name='invoice_ref',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
