# Generated by Django 3.0.1 on 2021-12-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0012_auto_20211227_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
