# Generated by Django 3.2.12 on 2022-08-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0014_auto_20220814_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicebucket',
            name='is_processing',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='invoiceque',
            name='is_processing',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='opque',
            name='is_processing',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='slipque',
            name='is_processing',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
