# Generated by Django 3.2.12 on 2022-09-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0015_auto_20220821_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='opque',
            name='is_invoice',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
