# Generated by Django 3.2.12 on 2022-09-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0016_opque_is_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicebucket',
            name='uid',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
