SELECT
  TOP 500
  CLC.CODE, 
  CLC.DEFINITION_, 
  POF.FICHENO, 
  POF.DATE_, 
  POFFERBEGDT, 
  POFFERENDDT, 
  ITM.CODE AS ITEMCODE, 
  ITM.NAME, 
  ITM.NAME4, 
  POL.PRICE, 
  SETL.CODE AS SETLCODE, 
  prC.PTYPE 'PRCLISTTYPE', 
  PRC.CODE 'PRCLISTCODE' 
FROM 
  LG_${NS}_PURCHOFFER POF 
  LEFT OUTER JOIN LG_${NS}_PURCHOFFERLN POL WITH (NOLOCK) ON POL.ORDFICHEREF = POF.LOGICALREF 
  LEFT OUTER JOIN LG_${NS}_CLCARD CLC WITH (NOLOCK) ON POF.CLIENTREF = CLC.LOGICALREF 
  LEFT OUTER JOIN LG_${NS}_ITEMS ITM WITH (NOLOCK) ON ITM.LOGICALREF = POL.STOCKREF 
  LEFT OUTER JOIN LG_${NS}_UNITSETL SETL WITH (NOLOCK) ON SETL.UNITSETREF = POL.USREF 
  AND SETL.LOGICALREF = POL.UOMREF 
  LEFT OUTER JOIN LG_${NS}_PRCLIST PRC WITH (NOLOCK) ON PRC.LOGICALREF = POL.PRCLISTREF 
WHERE 
  1 = 1 
  AND ITM.ACTIVE = 0
  ${WHERE}
