SELECT 
  ORF.LOGICALREF, 
  ORF.DATE_ 'FicheDate', 
  ORF.FICHENO 'FicheNo', 
  CLC.CODE 'AccountCode', 
  CLC.DEFINITION_ 'AccountName', 
  ITM.CODE 'ItemCode', 
  ITM.NAME 'ItemName', 
  ORF.BRANCH 'BRANCH', 
  ORF.DOCODE 'DocumentNo', 
  ORF.GENEXP1 'OrderExp1', 
  ORF.GENEXP2 'OrderExp2', 
  ORL.AMOUNT 'OrderAmount', 
  ORL.LOGICALREF 'LINEREF', 
  ORL.SHIPPEDAMOUNT 'ShippedAmount', 
  ORL.AMOUNT - ORL.SHIPPEDAMOUNT 'WaitingAmount', 
  ORL.DISCPER 'LineDiscRate', 
  ORL.PRICE 'Price', 
  ORL.VAT 'Vat', 
  ORL.DISTDISC 'DiscTotal', 
  UL.CODE 'Unit', 
  EMU.CODE 'GlCode', 
  SUM(
    CASE WHEN DISCPER > 0 THEN (VATMATRAH + VATAMNT) - (
      (
        (VATMATRAH + VATAMNT)* DISCPER
      )/ 100
    ) ELSE VATMATRAH + VATAMNT END
  ) 'OrderTotal', 
  (
    (ORL.AMOUNT - ORL.SHIPPEDAMOUNT) * SUM(
      CASE WHEN DISCPER > 0 THEN (VATMATRAH + VATAMNT) - (
        (
          (VATMATRAH + VATAMNT)* DISCPER
        )/ 100
      ) ELSE VATMATRAH + VATAMNT END
    )
  ) / ORL.AMOUNT 'WaitingTotal' 
FROM 
  LG_${NS}_${PER}_ORFLINE ORL WITH(NOLOCK) 
  LEFT OUTER JOIN LG_${NS}_${PER}_ORFICHE ORF WITH(NOLOCK) ON ORL.ORDFICHEREF = ORF.LOGICALREF 
  LEFT OUTER JOIN LG_${NS}_CLCARD CLC WITH(NOLOCK) ON CLC.LOGICALREF = ORF.CLIENTREF 
  LEFT OUTER JOIN LG_${NS}_ITEMS ITM WITH(NOLOCK) ON ITM.LOGICALREF = ORL.STOCKREF 
  LEFT OUTER JOIN LG_${NS}_UNITSETL UL WITH(NOLOCK) ON UL.LOGICALREF = ORL.UOMREF 
  LEFT OUTER JOIN LG_${NS}_CRDACREF CRD WITH(NOLOCK) ON CRD.CARDREF = ITM.LOGICALREF 
  AND CRD.TYP = 1 
  AND CRD.TRCODE = '1' 
  LEFT OUTER JOIN LG_${NS}_EMUHACC EMU WITH(NOLOCK) ON CRD.ACCOUNTREF = EMU.LOGICALREF 
WHERE 
  ORF.TRCODE = 2 
  AND ORL.LINETYPE = 0 
  AND ORL.AMOUNT - ORL.SHIPPEDAMOUNT > 0 
  AND ORL.CLOSED = 0 
  AND ORF.CANCELLED = 0 
  AND ORF.STATUS IN (1, 4)
  ${WHERE}

GROUP BY 
  ORF.LOGICALREF, 
  ORF.DATE_, 
  ORF.FICHENO, 
  ITM.CODE, 
  ITM.NAME, 
  ORL.AMOUNT, 
  ORL.SHIPPEDAMOUNT, 
  ORL.AMOUNT - ORL.SHIPPEDAMOUNT, 
  ORL.DISCPER, 
  ORL.PRICE, 
  ORL.VAT, 
  ORL.DISTDISC, 
  CLC.CODE, 
  CLC.DEFINITION_, 
  ITM.SPECODE, 
  ORF.DOCODE, 
  ORF.STATUS, 
  ORF.GENEXP1, 
  ORF.GENEXP2, 
  ORF.BRANCH, 
  ORL.LOGICALREF, 
  UL.CODE, 
  EMU.CODE
