# Generated by Django 3.0.1 on 2021-12-02 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=6, unique=True)),
                ('aws_access_key', models.CharField(max_length=255)),
                ('aws_access_secret', models.CharField(max_length=255)),
                ('bucket', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm', models.CharField(max_length=60)),
                ('identifier', models.CharField(max_length=128, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('flow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bti.Flow')),
            ],
            options={
                'abstract': False,
                'unique_together': {('firm', 'identifier')},
            },
        ),
        migrations.CreateModel(
            name='ItemTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm', models.CharField(max_length=60)),
                ('identifier', models.CharField(max_length=128, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('flow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bti.Flow')),
            ],
            options={
                'abstract': False,
                'unique_together': {('firm', 'identifier')},
            },
        ),
        migrations.CreateModel(
            name='ArpTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm', models.CharField(max_length=60)),
                ('identifier', models.CharField(max_length=128, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('flow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bti.Flow')),
            ],
            options={
                'abstract': False,
                'unique_together': {('firm', 'identifier')},
            },
        ),
    ]
