# Generated by Django 3.2.12 on 2022-04-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arptrack',
            name='is_processing',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='itemtrack',
            name='is_processing',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='ordertrack',
            name='is_processing',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='arptrack',
            name='id',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='itemtrack',
            name='id',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ordertrack',
            name='id',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='s3resource',
            name='id',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
