# Generated by Django 4.0.8 on 2023-02-15 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '__first__'),
        ('app_v1', '0004_auto_20220514_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='iStfiche',
            fields=[
                ('lg_stfiche_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erp.lg_stfiche')),
                ('capiblock_created_by', models.SmallIntegerField(blank=True, db_column='CAPIBLOCK_CREATEDBY', null=True)),
                ('capiblock_created_date', models.SmallIntegerField(blank=True, db_column='CAPIBLOCK_CREADEDDATE', null=True)),
                ('capiblock_created_hour', models.SmallIntegerField(blank=True, db_column='CAPIBLOCK_CREATEDHOUR', null=True)),
                ('capiblock_created_min', models.SmallIntegerField(blank=True, db_column='CAPIBLOCK_CREATEDMIN', null=True)),
                ('capiblock_created_sec', models.SmallIntegerField(blank=True, db_column='CAPIBLOCK_CREATEDSEC', null=True)),
            ],
            options={
                'db_table': 'LG_011_01_STFICHE',
                'managed': False,
                'target_db': 'erp',
            },
            bases=('erp.lg_stfiche',),
        ),
    ]
