# Generated by Django 3.2.12 on 2023-08-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_v1', '0005_istfiche'),
    ]

    operations = [
        migrations.DeleteModel(
            name='iStfiche',
        ),
    ]
