"""
 Tüm hakları BTI Bilişim Danışmanlık ve Yazılım Şirketi adına saklıdır.
 
"""

from django.db import models
from erp.models.base import *

class L_CAPIDIV(
    BaseLogical,
    models.Model):
    firm = models.ForeignKey(
        "L_CAPIFIRM",
        db_column='FIRMNR',
        blank=True,
        null=True,
        to_field='nr',
        on_delete=models.DO_NOTHING
    )
    nr = models.SmallIntegerField(unique=True, db_column='NR', blank=True, null=True)
    name = models.CharField(db_column='NAME', max_length=61, blank=True, null=True)
    street = models.CharField(db_column='STREET', max_length=21, blank=True, null=True)
    road = models.CharField(db_column='ROAD', max_length=21, blank=True, null=True)
    doornr = models.CharField(db_column='DOORNR', max_length=21, blank=True, null=True)
    district = models.CharField(db_column='DISTRICT', max_length=21, blank=True, null=True)
    city = models.CharField(db_column='CITY', max_length=21, blank=True, null=True)
    country = models.CharField(db_column='COUNTRY', max_length=21, blank=True, null=True)
    zipcode = models.CharField(db_column='ZIPCODE', max_length=11, blank=True, null=True)
    phone = models.CharField(db_column='PHONE', max_length=16, blank=True, null=True)
    fax = models.CharField(db_column='FAX', max_length=16, blank=True, null=True)
    taxoff = models.CharField(db_column='TAXOFF', max_length=51, blank=True, null=True)
    taxnr = models.CharField(db_column='TAXNR', max_length=21, blank=True, null=True)
    securnr = models.CharField(db_column='SECURNR', max_length=51, blank=True, null=True)
    siteid = models.SmallIntegerField(db_column='SITEID', blank=True, null=True)
    userext = models.IntegerField(db_column='USEREXT', blank=True, null=True)
    taxoffcode = models.CharField(db_column='TAXOFFCODE', max_length=25, blank=True, null=True)
    cntrycode = models.CharField(db_column='CNTRYCODE', max_length=5, blank=True, null=True)
    moddate = models.DateTimeField(db_column='MODDATE', blank=True, null=True)
    modtime = models.IntegerField(db_column='MODTIME', blank=True, null=True)
    iskurnr = models.CharField(db_column='ISKURNR', max_length=51, blank=True, null=True)
    founddate = models.DateTimeField(db_column='FOUNDDATE', blank=True, null=True)
    iskurdept = models.CharField(db_column='ISKURDEPT', max_length=51, blank=True, null=True)
    indsector = models.CharField(db_column='INDSECTOR', max_length=51, blank=True, null=True)
    logoid = models.CharField(db_column='LOGOID', max_length=25, blank=True, null=True)
    sgkusername = models.CharField(db_column='SGKUSERNAME', max_length=33, blank=True, null=True)
    sgkusercode = models.CharField(db_column='SGKUSERCODE', max_length=33, blank=True, null=True)
    sgksyspass = models.CharField(db_column='SGKSYSPASS', max_length=33, blank=True, null=True)
    divpassword = models.CharField(db_column='DIVPASSWORD', max_length=33, blank=True, null=True)
    iskurtckno = models.CharField(db_column='ISKURTCKNO', max_length=33, blank=True, null=True)
    iskurpass = models.CharField(db_column='ISKURPASS', max_length=33, blank=True, null=True)
    csgbworkcode = models.CharField(db_column='CSGBWORKCODE', max_length=6, blank=True, null=True)
    csgbfileno = models.CharField(db_column='CSGBFILENO', max_length=21, blank=True, null=True)
    passive = models.SmallIntegerField(db_column='PASSIVE', blank=True, null=True)
    useeinv = models.SmallIntegerField(db_column='USEEINV', blank=True, null=True)
    postlabelcode = models.CharField(db_column='POSTLABELCODE', max_length=101, blank=True, null=True)
    senderlabelcode = models.CharField(db_column='SENDERLABELCODE', max_length=101, blank=True, null=True)
    webadd = models.CharField(db_column='WEBADD', max_length=41, blank=True, null=True)
    emailaddr = models.CharField(db_column='EMAILADDR', max_length=51, blank=True, null=True)
    firmtype = models.SmallIntegerField(db_column='FIRMTYPE', blank=True, null=True)
    nacecode = models.CharField(db_column='NACECODE', max_length=65, blank=True, null=True)
    useebook = models.SmallIntegerField(db_column='USEEBOOK', blank=True, null=True)
    traderegisno = models.CharField(db_column='TRADEREGISNO', max_length=21, blank=True, null=True)
    mersisno = models.CharField(db_column='MERSISNO', max_length=51, blank=True, null=True)
    title = models.CharField(db_column='TITLE', max_length=51, blank=True, null=True)
    ebookfileno = models.SmallIntegerField(db_column='EBOOKFILENO', blank=True, null=True)
    useearchive = models.SmallIntegerField(db_column='USEEARCHIVE', blank=True, null=True)
    intsalesaddr = models.CharField(db_column='INTSALESADDR', max_length=101, blank=True, null=True)
    ebookstartdate = models.DateTimeField(db_column='EBOOKSTARTDATE', blank=True, null=True)
    ebookdivname = models.CharField(db_column='EBOOKDIVNAME', max_length=61, blank=True, null=True)
    ebookfirmname = models.CharField(db_column='EBOOKFIRMNAME', max_length=61, blank=True, null=True)
    ebookfirmtitle = models.CharField(db_column='EBOOKFIRMTITLE', max_length=51, blank=True, null=True)
    ebookcurrtype = models.SmallIntegerField(db_column='EBOOKCURRTYPE', blank=True, null=True)
    earcentsend = models.SmallIntegerField(db_column='EARCENTSEND', blank=True, null=True)
    earcentuser = models.CharField(db_column='EARCENTUSER', max_length=51, blank=True, null=True)
    earcentpass = models.CharField(db_column='EARCENTPASS', max_length=51, blank=True, null=True)
    earcentdefaddr = models.CharField(db_column='EARCENTDEFADDR', max_length=251, blank=True, null=True)
    lastcontrolno = models.IntegerField(db_column='LASTCONTROLNO', blank=True, null=True)
    lastjournalno = models.IntegerField(db_column='LASTJOURNALNO', blank=True, null=True)
    lastgloblineno = models.IntegerField(db_column='LASTGLOBLINENO', blank=True, null=True)
    backupebooks = models.SmallIntegerField(db_column='BACKUPEBOOKS', blank=True, null=True)
    einvcustom = models.SmallIntegerField(db_column='EINVCUSTOM', blank=True, null=True)
    einvoicetypsgk = models.SmallIntegerField(db_column='EINVOICETYPSGK', blank=True, null=True)
    taxpayercode = models.CharField(db_column='TAXPAYERCODE', max_length=101, blank=True, null=True)
    taxpayername = models.CharField(db_column='TAXPAYERNAME', max_length=101, blank=True, null=True)
    cpatitle = models.SmallIntegerField(db_column='CPATITLE', blank=True, null=True)
    cpaidtcno = models.CharField(db_column='CPAIDTCNO', max_length=21, blank=True, null=True)
    cpaname = models.CharField(db_column='CPANAME', max_length=31, blank=True, null=True)
    cpasurname = models.CharField(db_column='CPASURNAME', max_length=31, blank=True, null=True)
    cpastreet = models.CharField(db_column='CPASTREET', max_length=21, blank=True, null=True)
    cparoad = models.CharField(db_column='CPAROAD', max_length=21, blank=True, null=True)
    cpadoornr = models.CharField(db_column='CPADOORNR', max_length=21, blank=True, null=True)
    cpadistrict = models.CharField(db_column='CPADISTRICT', max_length=21, blank=True, null=True)
    cpacity = models.CharField(db_column='CPACITY', max_length=21, blank=True, null=True)
    cpaphone = models.CharField(db_column='CPAPHONE', max_length=16, blank=True, null=True)
    cpataxoff = models.CharField(db_column='CPATAXOFF', max_length=51, blank=True, null=True)
    cpataxnr = models.CharField(db_column='CPATAXNR', max_length=21, blank=True, null=True)
    cpachambnr = models.CharField(db_column='CPACHAMBNR', max_length=21, blank=True, null=True)
    cpaemail = models.CharField(db_column='CPAEMAIL', max_length=51, blank=True, null=True)
    cpausercode = models.CharField(db_column='CPAUSERCODE', max_length=25, blank=True, null=True)
    cpaparole = models.CharField(db_column='CPAPAROLE', max_length=25, blank=True, null=True)
    cpapasswordtaxdecl = models.CharField(db_column='CPAPASSWORDTAXDECL', max_length=25, blank=True, null=True)
    cpacntrycode = models.CharField(db_column='CPACNTRYCODE', max_length=5, blank=True, null=True)
    cpacountry = models.CharField(db_column='CPACOUNTRY', max_length=21, blank=True, null=True)
    cpazipcode = models.CharField(db_column='CPAZIPCODE', max_length=11, blank=True, null=True)
    cpafaxnr = models.CharField(db_column='CPAFAXNR', max_length=16, blank=True, null=True)
    cpacontractdesc = models.CharField(db_column='CPACONTRACTDESC', max_length=51, blank=True, null=True)
    cpacontracttype = models.CharField(db_column='CPACONTRACTTYPE', max_length=51, blank=True, null=True)
    cpacontractdate = models.DateTimeField(db_column='CPACONTRACTDATE', blank=True, null=True)
    cpacontractnumber = models.CharField(db_column='CPACONTRACTNUMBER', max_length=51, blank=True, null=True)
    cpaisebookkeptbyfirm = models.SmallIntegerField(db_column='CPAISEBOOKKEPTBYFIRM', blank=True, null=True)
    cpaisymmcontractmade = models.SmallIntegerField(db_column='CPAISYMMCONTRACTMADE', blank=True, null=True)
    cpaymmname = models.CharField(db_column='CPAYMMNAME', max_length=31, blank=True, null=True)
    cpaymmcontdesc = models.CharField(db_column='CPAYMMCONTDESC', max_length=51, blank=True, null=True)
    cpaymmconttype = models.CharField(db_column='CPAYMMCONTTYPE', max_length=51, blank=True, null=True)
    cpaymmphone = models.CharField(db_column='CPAYMMPHONE', max_length=16, blank=True, null=True)
    cpaymmemail = models.CharField(db_column='CPAYMMEMAIL', max_length=51, blank=True, null=True)
    cpaymmsurname = models.CharField(db_column='CPAYMMSURNAME', max_length=31, blank=True, null=True)
    cpaymmcontdate = models.DateTimeField(db_column='CPAYMMCONTDATE', blank=True, null=True)
    cpaymmcontnumber = models.CharField(db_column='CPAYMMCONTNUMBER', max_length=51, blank=True, null=True)
    cpaymmfaxnr = models.CharField(db_column='CPAYMMFAXNR', max_length=16, blank=True, null=True)
    useedespatch = models.SmallIntegerField(db_column='USEEDESPATCH', blank=True, null=True)
    postlabelcodedesp = models.CharField(db_column='POSTLABELCODEDESP', max_length=101, blank=True, null=True)
    senderlabelcodedesp = models.CharField(db_column='SENDERLABELCODEDESP', max_length=101, blank=True, null=True)
    useeproducerrec = models.SmallIntegerField(db_column='USEEPRODUCERREC', blank=True, null=True)
    useetradesmaninv = models.SmallIntegerField(db_column='USEETRADESMANINV', blank=True, null=True)
    usepaperinv = models.SmallIntegerField(db_column='USEPAPERINV', blank=True, null=True)
    earchivetype = models.SmallIntegerField(db_column='EARCHIVETYPE', blank=True, null=True)
    locbranchaddressnr = models.CharField(db_column='LOCBRANCHADDRESSNR', max_length=11, blank=True, null=True)
    propertystatus = models.SmallIntegerField(db_column='PROPERTYSTATUS', blank=True, null=True)
    locbranchcode = models.CharField(db_column='LOCBRANCHCODE', max_length=11, blank=True, null=True)
    traderegcode = models.SmallIntegerField(db_column='TRADEREGCODE', blank=True, null=True)
    locationtype = models.SmallIntegerField(db_column='LOCATIONTYPE', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'L_CAPIDIV'
        unique_together = (('firm', 'nr'),)
        target_db = 'system'

    def __str__(self):
        return f'{self.nr} {self.name}'
