"""
 Tüm hakları BTI Bilişim Danışmanlık ve Yazılım Şirketi adına saklıdır.
 
"""

from django.db import models

class L_CAPIFIRM(models.Model):
    logicalref = models.AutoField(db_column='LOGICALREF', primary_key=True)
    nr = models.SmallIntegerField(db_column='NR', unique=True, blank=True, null=True)
    name = models.CharField(db_column='NAME', max_length=61, blank=True, null=True)
    title = models.CharField(db_column='TITLE', max_length=51, blank=True, null=True)
    street = models.CharField(db_column='STREET', max_length=21, blank=True, null=True)
    road = models.CharField(db_column='ROAD', max_length=21, blank=True, null=True)
    doornr = models.CharField(db_column='DOORNR', max_length=21, blank=True, null=True)
    district = models.CharField(db_column='DISTRICT', max_length=21, blank=True, null=True)
    city = models.CharField(db_column='CITY', max_length=21, blank=True, null=True)
    country = models.CharField(db_column='COUNTRY', max_length=21, blank=True, null=True)
    zipcode = models.CharField(db_column='ZIPCODE', max_length=11, blank=True, null=True)
    phone1 = models.CharField(db_column='PHONE1', max_length=16, blank=True, null=True)
    phone2 = models.CharField(db_column='PHONE2', max_length=16, blank=True, null=True)
    fax = models.CharField(db_column='FAX', max_length=16, blank=True, null=True)
    taxoff = models.CharField(db_column='TAXOFF', max_length=51, blank=True, null=True)
    taxnr = models.CharField(db_column='TAXNR', max_length=21, blank=True, null=True)
    securnr = models.CharField(db_column='SECURNR', max_length=51, blank=True, null=True)
    direct = models.CharField(db_column='DIRECT', max_length=81, blank=True, null=True)
    cpaname = models.CharField(db_column='CPANAME', max_length=31, blank=True, null=True)
    cpastreet = models.CharField(db_column='CPASTREET', max_length=21, blank=True, null=True)
    cparoad = models.CharField(db_column='CPAROAD', max_length=21, blank=True, null=True)
    cpadoornr = models.CharField(db_column='CPADOORNR', max_length=21, blank=True, null=True)
    cpadistrict = models.CharField(db_column='CPADISTRICT', max_length=21, blank=True, null=True)
    cpacity = models.CharField(db_column='CPACITY', max_length=21, blank=True, null=True)
    cpaphone = models.CharField(db_column='CPAPHONE', max_length=16, blank=True, null=True)
    cpataxoff = models.CharField(db_column='CPATAXOFF', max_length=51, blank=True, null=True)
    cpataxnr = models.CharField(db_column='CPATAXNR', max_length=21, blank=True, null=True)
    cpachambnr = models.CharField(db_column='CPACHAMBNR', max_length=21, blank=True, null=True)
    begmon = models.SmallIntegerField(db_column='BEGMON', blank=True, null=True)
    begday = models.SmallIntegerField(db_column='BEGDAY', blank=True, null=True)
    userext = models.IntegerField(db_column='USEREXT', blank=True, null=True)
    pernr = models.SmallIntegerField(db_column='PERNR', blank=True, null=True)
    countofleg = models.SmallIntegerField(db_column='COUNTOFLEG', blank=True, null=True)
    ctable = models.CharField(db_column='CTABLE', max_length=31, blank=True, null=True)
    workdayflgs1 = models.SmallIntegerField(db_column='WORKDAYFLGS1', blank=True, null=True)
    workdayflgs2 = models.SmallIntegerField(db_column='WORKDAYFLGS2', blank=True, null=True)
    workdayflgs3 = models.SmallIntegerField(db_column='WORKDAYFLGS3', blank=True, null=True)
    workdayflgs4 = models.SmallIntegerField(db_column='WORKDAYFLGS4', blank=True, null=True)
    workdayflgs5 = models.SmallIntegerField(db_column='WORKDAYFLGS5', blank=True, null=True)
    workdayflgs6 = models.SmallIntegerField(db_column='WORKDAYFLGS6', blank=True, null=True)
    workdayflgs7 = models.SmallIntegerField(db_column='WORKDAYFLGS7', blank=True, null=True)
    localctyp = models.SmallIntegerField(db_column='LOCALCTYP', blank=True, null=True)
    firmrepcurr = models.SmallIntegerField(db_column='FIRMREPCURR', blank=True, null=True)
    sepexchtable = models.SmallIntegerField(db_column='SEPEXCHTABLE', blank=True, null=True)
    vatroundmtd = models.SmallIntegerField(db_column='VATROUNDMTD', blank=True, null=True)
    firmeuvatnumber = models.CharField(db_column='FIRMEUVATNUMBER', max_length=21, blank=True, null=True)
    majversnr = models.SmallIntegerField(db_column='MAJVERSNR', blank=True, null=True)
    minversnr = models.SmallIntegerField(db_column='MINVERSNR', blank=True, null=True)
    relversnr = models.SmallIntegerField(db_column='RELVERSNR', blank=True, null=True)
    siteid = models.SmallIntegerField(db_column='SITEID', blank=True, null=True)
    orgchart = models.IntegerField(db_column='ORGCHART', blank=True, null=True)
    localcaldr = models.SmallIntegerField(db_column='LOCALCALDR', blank=True, null=True)
    firmlang = models.SmallIntegerField(db_column='FIRMLANG', blank=True, null=True)
    taxoffcode = models.CharField(db_column='TAXOFFCODE', max_length=25, blank=True, null=True)
    cntrycode = models.CharField(db_column='CNTRYCODE', max_length=5, blank=True, null=True)
    longperiods = models.SmallIntegerField(db_column='LONGPERIODS', blank=True, null=True)
    logoid = models.CharField(db_column='LOGOID', max_length=25, blank=True, null=True)
    emailaddr = models.CharField(db_column='EMAILADDR', max_length=31, blank=True, null=True)
    webaddr = models.CharField(db_column='WEBADDR', max_length=41, blank=True, null=True)
    moddate = models.DateTimeField(db_column='MODDATE', blank=True, null=True)
    modtime = models.IntegerField(db_column='MODTIME', blank=True, null=True)
    traderegisno = models.CharField(db_column='TRADEREGISNO', max_length=21, blank=True, null=True)
    employername = models.CharField(db_column='EMPLOYERNAME', max_length=21, blank=True, null=True)
    employersurname = models.CharField(db_column='EMPLOYERSURNAME', max_length=21, blank=True, null=True)
    employeridtcno = models.CharField(db_column='EMPLOYERIDTCNO', max_length=21, blank=True, null=True)
    employeremail = models.CharField(db_column='EMPLOYEREMAIL', max_length=51, blank=True, null=True)
    firmytlstatus = models.SmallIntegerField(db_column='FIRMYTLSTATUS', blank=True, null=True)
    ytlsourcefirm = models.SmallIntegerField(db_column='YTLSOURCEFIRM', blank=True, null=True)
    zusatzno = models.CharField(db_column='ZUSATZNO', max_length=4, blank=True, null=True)
    taxoffstatecd = models.CharField(db_column='TAXOFFSTATECD', max_length=13, blank=True, null=True)
    taxoffstatenm = models.CharField(db_column='TAXOFFSTATENM', max_length=41, blank=True, null=True)
    statecode = models.CharField(db_column='STATECODE', max_length=13, blank=True, null=True)
    statename = models.CharField(db_column='STATENAME', max_length=41, blank=True, null=True)
    cpaoccupation = models.CharField(db_column='CPAOCCUPATION', max_length=51, blank=True, null=True)
    cpaextension = models.CharField(db_column='CPAEXTENSION', max_length=17, blank=True, null=True)
    cpaemail = models.CharField(db_column='CPAEMAIL', max_length=51, blank=True, null=True)
    cpasurname = models.CharField(db_column='CPASURNAME', max_length=31, blank=True, null=True)
    cpaidtcno = models.CharField(db_column='CPAIDTCNO', max_length=21, blank=True, null=True)
    accofficecode = models.CharField(db_column='ACCOFFICECODE', max_length=17, blank=True, null=True)
    advancedproduct = models.SmallIntegerField(db_column='ADVANCEDPRODUCT', blank=True, null=True)
    bagkurnr = models.CharField(db_column='BAGKURNR', max_length=11, blank=True, null=True)
    username = models.CharField(db_column='USERNAME', max_length=31, blank=True, null=True)
    dbname = models.CharField(db_column='DBNAME', max_length=81, blank=True, null=True)
    password = models.CharField(db_column='PASSWORD', max_length=31, blank=True, null=True)
    actarea = models.SmallIntegerField(db_column='ACTAREA', blank=True, null=True)
    sector = models.SmallIntegerField(db_column='SECTOR', blank=True, null=True)
    srccriteria = models.CharField(db_column='SRCCRITERIA', max_length=51, blank=True, null=True)
    conscoderef = models.IntegerField(db_column='CONSCODEREF', blank=True, null=True)
    tcellappid = models.CharField(db_column='TCELLAPPID', max_length=81, blank=True, null=True)
    tcellapppw = models.CharField(db_column='TCELLAPPPW', max_length=32, blank=True, null=True)
    dncnstlen = models.SmallIntegerField(db_column='DNCNSTLEN', blank=True, null=True)
    useserverdate = models.SmallIntegerField(db_column='USESERVERDATE', blank=True, null=True)
    usechangelog = models.SmallIntegerField(db_column='USECHANGELOG', blank=True, null=True)
    mobusername = models.CharField(db_column='MOBUSERNAME', max_length=31, blank=True, null=True)
    mobpassword = models.CharField(db_column='MOBPASSWORD', max_length=31, blank=True, null=True)
    mobfirmalias = models.CharField(db_column='MOBFIRMALIAS', max_length=31, blank=True, null=True)
    accepteinv = models.SmallIntegerField(db_column='ACCEPTEINV', blank=True, null=True)
    einvoiceid = models.CharField(db_column='EINVOICEID', max_length=41, blank=True, null=True)
    profileid = models.CharField(db_column='PROFILEID', max_length=41, blank=True, null=True)
    usecommonparam = models.SmallIntegerField(db_column='USECOMMONPARAM', blank=True, null=True)
    passive = models.SmallIntegerField(db_column='PASSIVE', blank=True, null=True)
    usercode = models.CharField(db_column='USERCODE', max_length=25, blank=True, null=True)
    parole = models.CharField(db_column='PAROLE', max_length=25, blank=True, null=True)
    passwordtaxdecl = models.CharField(db_column='PASSWORDTAXDECL', max_length=25, blank=True, null=True)
    firmemailaddr = models.CharField(db_column='FIRMEMAILADDR', max_length=51, blank=True, null=True)
    firmtype = models.SmallIntegerField(db_column='FIRMTYPE', blank=True, null=True)
    nacecode = models.CharField(db_column='NACECODE', max_length=65, blank=True, null=True)
    cpacountry = models.CharField(db_column='CPACOUNTRY', max_length=21, blank=True, null=True)
    cpazipcode = models.CharField(db_column='CPAZIPCODE', max_length=11, blank=True, null=True)
    cpafaxnr = models.CharField(db_column='CPAFAXNR', max_length=16, blank=True, null=True)
    cpacntrycode = models.CharField(db_column='CPACNTRYCODE', max_length=5, blank=True, null=True)
    useebook = models.SmallIntegerField(db_column='USEEBOOK', blank=True, null=True)
    contractdesc = models.CharField(db_column='CONTRACTDESC', max_length=51, blank=True, null=True)
    contracttype = models.CharField(db_column='CONTRACTTYPE', max_length=51, blank=True, null=True)
    contractdate = models.DateTimeField(db_column='CONTRACTDATE', blank=True, null=True)
    contractnumber = models.CharField(db_column='CONTRACTNUMBER', max_length=51, blank=True, null=True)
    hashvers = models.CharField(db_column='HASHVERS', max_length=51, blank=True, null=True)
    timestampuser = models.CharField(db_column='TIMESTAMPUSER', max_length=31, blank=True, null=True)
    timestamppass = models.CharField(db_column='TIMESTAMPPASS', max_length=31, blank=True, null=True)
    timestampserver = models.CharField(db_column='TIMESTAMPSERVER', max_length=201, blank=True, null=True)
    useproxy = models.SmallIntegerField(db_column='USEPROXY', blank=True, null=True)
    ptimestampuser = models.CharField(db_column='PTIMESTAMPUSER', max_length=31, blank=True, null=True)
    ptimestamppass = models.CharField(db_column='PTIMESTAMPPASS', max_length=31, blank=True, null=True)
    ptimestamphost = models.CharField(db_column='PTIMESTAMPHOST', max_length=201, blank=True, null=True)
    ptimestampport = models.IntegerField(db_column='PTIMESTAMPPORT', blank=True, null=True)
    timestampport = models.IntegerField(db_column='TIMESTAMPPORT', blank=True, null=True)
    timestampapppth = models.CharField(db_column='TIMESTAMPAPPPTH', max_length=201, blank=True, null=True)
    jgserverurl = models.CharField(db_column='JGSERVERURL', max_length=201, blank=True, null=True)
    jgusername = models.CharField(db_column='JGUSERNAME', max_length=51, blank=True, null=True)
    jgpassword = models.CharField(db_column='JGPASSWORD', max_length=51, blank=True, null=True)
    jgcompanynr = models.IntegerField(db_column='JGCOMPANYNR', blank=True, null=True)
    jgperiodnr = models.IntegerField(db_column='JGPERIODNR', blank=True, null=True)
    jghrfirmcode = models.CharField(db_column='JGHRFIRMCODE', max_length=61, blank=True, null=True)
    deductlimit = models.FloatField(db_column='DEDUCTLIMIT', blank=True, null=True)
    postlabelcode = models.CharField(db_column='POSTLABELCODE', max_length=101, blank=True, null=True)
    senderlabelcode = models.CharField(db_column='SENDERLABELCODE', max_length=101, blank=True, null=True)
    einvconttype = models.SmallIntegerField(db_column='EINVCONTTYPE', blank=True, null=True)
    ebookconttype = models.SmallIntegerField(db_column='EBOOKCONTTYPE', blank=True, null=True)
    mersisno = models.CharField(db_column='MERSISNO', max_length=51, blank=True, null=True)
    officaltitle = models.CharField(db_column='OFFICALTITLE', max_length=255, blank=True, null=True)
    useearchive = models.SmallIntegerField(db_column='USEEARCHIVE', blank=True, null=True)
    intsalesaddr = models.CharField(db_column='INTSALESADDR', max_length=101, blank=True, null=True)
    faxusername = models.CharField(db_column='FAXUSERNAME', max_length=51, blank=True, null=True)
    faxuserkey = models.CharField(db_column='FAXUSERKEY', max_length=51, blank=True, null=True)
    faxemailaddr = models.CharField(db_column='FAXEMAILADDR', max_length=51, blank=True, null=True)
    ebookstartdate = models.DateTimeField(db_column='EBOOKSTARTDATE', blank=True, null=True)
    ebookcurrtype = models.SmallIntegerField(db_column='EBOOKCURRTYPE', blank=True, null=True)
    earcentsend = models.SmallIntegerField(db_column='EARCENTSEND', blank=True, null=True)
    earcentuser = models.CharField(db_column='EARCENTUSER', max_length=51, blank=True, null=True)
    earcentpass = models.CharField(db_column='EARCENTPASS', max_length=51, blank=True, null=True)
    earcentdefaddr = models.CharField(db_column='EARCENTDEFADDR', max_length=251, blank=True, null=True)
    cpatitle = models.SmallIntegerField(db_column='CPATITLE', blank=True, null=True)
    isebookkeptbyfirm = models.SmallIntegerField(db_column='ISEBOOKKEPTBYFIRM', blank=True, null=True)
    isymmcontractmade = models.SmallIntegerField(db_column='ISYMMCONTRACTMADE', blank=True, null=True)
    ymmname = models.CharField(db_column='YMMNAME', max_length=31, blank=True, null=True)
    ymmsurname = models.CharField(db_column='YMMSURNAME', max_length=31, blank=True, null=True)
    ymmcontdesc = models.CharField(db_column='YMMCONTDESC', max_length=51, blank=True, null=True)
    ymmconttype = models.CharField(db_column='YMMCONTTYPE', max_length=51, blank=True, null=True)
    ymmcontdate = models.IntegerField(db_column='YMMCONTDATE', blank=True, null=True)
    ymmcontnumber = models.CharField(db_column='YMMCONTNUMBER', max_length=51, blank=True, null=True)
    lastcontrolno = models.IntegerField(db_column='LASTCONTROLNO', blank=True, null=True)
    lastjournalno = models.IntegerField(db_column='LASTJOURNALNO', blank=True, null=True)
    lastgloblineno = models.IntegerField(db_column='LASTGLOBLINENO', blank=True, null=True)
    backupebooks = models.SmallIntegerField(db_column='BACKUPEBOOKS', blank=True, null=True)
    einvcustom = models.SmallIntegerField(db_column='EINVCUSTOM', blank=True, null=True)
    ymmphone = models.CharField(db_column='YMMPHONE', max_length=16, blank=True, null=True)
    ymmfaxnr = models.CharField(db_column='YMMFAXNR', max_length=16, blank=True, null=True)
    ymmemail = models.CharField(db_column='YMMEMAIL', max_length=51, blank=True, null=True)
    einvoicetypsgk = models.SmallIntegerField(db_column='EINVOICETYPSGK', blank=True, null=True)
    taxpayercode = models.CharField(db_column='TAXPAYERCODE', max_length=101, blank=True, null=True)
    taxpayername = models.CharField(db_column='TAXPAYERNAME', max_length=101, blank=True, null=True)
    ymmchambnr = models.CharField(db_column='YMMCHAMBNR', max_length=21, blank=True, null=True)
    ymmtcno = models.CharField(db_column='YMMTCNO', max_length=21, blank=True, null=True)
    ymmtaxnr = models.CharField(db_column='YMMTAXNR', max_length=21, blank=True, null=True)
    useedespatch = models.SmallIntegerField(db_column='USEEDESPATCH', blank=True, null=True)
    postlabelcodedesp = models.CharField(db_column='POSTLABELCODEDESP', max_length=101, blank=True, null=True)
    senderlabelcodedesp = models.CharField(db_column='SENDERLABELCODEDESP', max_length=101, blank=True, null=True)
    shaalgorithm = models.SmallIntegerField(db_column='SHAALGORITHM', blank=True, null=True)
    useeproducerrec = models.SmallIntegerField(db_column='USEEPRODUCERREC', blank=True, null=True)
    useetradesmaninv = models.SmallIntegerField(db_column='USEETRADESMANINV', blank=True, null=True)
    liquidatedfirm = models.SmallIntegerField(db_column='LIQUIDATEDFIRM', blank=True, null=True)
    liquidatingdate = models.IntegerField(db_column='LIQUIDATINGDATE', blank=True, null=True)
    cpatckn = models.SmallIntegerField(db_column='CPATCKN', blank=True, null=True)
    usepaperinv = models.SmallIntegerField(db_column='USEPAPERINV', blank=True, null=True)
    cpakdspassword = models.CharField(db_column='CPAKDSPASSWORD', max_length=51, blank=True, null=True)
    cpausername = models.CharField(db_column='CPAUSERNAME', max_length=51, blank=True, null=True)
    liquidationtyp = models.SmallIntegerField(db_column='LIQUIDATIONTYP', blank=True, null=True)
    getcpafromdiv = models.SmallIntegerField(db_column='GETCPAFROMDIV', blank=True, null=True)
    shpagncod = models.CharField(db_column='SHPAGNCOD', max_length=13, blank=True, null=True)
    usercode2 = models.CharField(db_column='USERCODE2', max_length=25, blank=True, null=True)
    parole2 = models.CharField(db_column='PAROLE2', max_length=25, blank=True, null=True)
    passwordtaxdecl2 = models.CharField(db_column='PASSWORDTAXDECL2', max_length=25, blank=True, null=True)
    emutentpass = models.CharField(db_column='EMUTENTPASS', max_length=51, blank=True, null=True)
    emutentdefaddr = models.CharField(db_column='EMUTENTDEFADDR', max_length=251, blank=True, null=True)
    emutentsend = models.SmallIntegerField(db_column='EMUTENTSEND', blank=True, null=True)
    emutentuser = models.CharField(db_column='EMUTENTUSER', max_length=51, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'L_CAPIFIRM'
        target_db = 'system'

    def __str__(self):
        return f'{self.nr} - {self.name}'


class L_FIRMPARAMS(models.Model):
    logicalref = models.AutoField(db_column='LOGICALREF', primary_key=True)
    firm = models.ForeignKey(
        L_CAPIFIRM, 
        db_column='FIRMNR',
        blank=True,
        null=True,
        to_field='nr',
        on_delete=models.DO_NOTHING
    )
    modulenr = models.SmallIntegerField(db_column='MODULENR', blank=True, null=True)
    groupnr = models.SmallIntegerField(db_column='GROUPNR', blank=True, null=True)
    code = models.CharField(db_column='CODE', max_length=25, blank=True, null=True)
    value = models.CharField(db_column='VALUE', max_length=201, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'L_FIRMPARAMS'
        unique_together = (('firm', 'code'),)
        target_db = 'system'

    def __str__(self):
        return f'{self.code} {self.value}'
